wevm/wagmi

docs/pages/docs/hooks/useEnsResolver.mdx
=> Docs: Fix `name` key in `useEnsResolver`

docs/pages/docs/hooks/useWaitForTransaction.mdx
Let's start with something small :)
=> docs: use correct import

docs/pages/guides/sign-message.mdx
This library is absolutely excellent! 👍 
Small typo in the docs (this one stumped me for a little bit because I was blindly copying and pasting the example code).
=> Update sign message example to use form component

CONTRIBUTING.md, docs/pages/docs/connectors.mdx, docs/pages/docs/hooks/useTransaction.mdx, docs/pages/docs/hooks/useWaitForTransaction.mdx, docs/pages/docs/provider.mdx, docs/pages/guides/sign-message.mdx
This MR proposes a couple of small text changes in the documentation to hopefully improve readability. I've also added a "Prerequisites" section to the Contributing guide and included PnpM since it's (currently) somewhat novel in the React community.
It also includes [a fix for an incorrect example](https://github.com/tmm/wagmi/pull/62/files#diff-df5ba1319640474ce1808686c384c97a62fabed337bd19953729a7696c1ba5d2R70).
=> docs: small documentation updates

.changeset/seven-shoes-battle.md, package.json, packages/react/package.json, pnpm-lock.yaml
potential resolution for #60 #65
=> fix: broken module exports

docs/pages/docs/connectors.mdx
=> Update docs link

docs/pages/docs/hooks/useContractWrite.mdx
Hello!
I've stumbled upon this typo while reading the doc. Please let me know if it wasn't a typo tho I might be wrong!
Thanks for this awesome library btw, really useful and powerful!
=> Typo in useContractWrite docs

packages/private/src/constants/chains.ts
This adds Avalanche Mainnet and Fuji chains to constants
=> Add support for Avalanche chain

packages/private/package.json, packages/private/src/connectors/walletConnect.ts, packages/private/src/connectors/walletLink.ts, packages/react/package.json, pnpm-lock.yaml
Didn't think you could request to switch with WalletConnect and WalletLink, but looks like you can. Couple notes:
- WalletLink works great
- WalletConnect doesn't have universal support so going to go with an [allowlist](https://github.com/tmm/wagmi/pull/115/files#diff-258c5b7b1b5ce8815a3895008c39602c860d11ffd5078f2617569560710e2641R10) for now.
h/t @markdalgleish
=> feat: add switch chain for walletconnect and walletlink

docs/pages/docs/connectors/injected.mdx
Your ENS/address: danizord.eth
=> Fix connector class name

.changeset/neat-parrots-shout.md, docs/pages/docs/provider.mdx, packages/react/src/index.test.ts, packages/react/src/index.ts
As discussed in https://github.com/tmm/wagmi/discussions/158.
Your ENS/address: markdalgleish.eth 👋
=> feat: add WagmiProvider alias for Provider

docs/pages/guides/connect-wallet.mdx
Updated the map in Step 2 from being `x` to `connector` so to be clearer with variable names
Your ENS/address: riklomas.eth
=> Changed documentation for Connect Wallet

docs/pages/docs/hooks/meta.json, docs/pages/docs/hooks/useEnsResolveName.mdx, packages/react/src/hooks/accounts/useBalance.ts, packages/react/src/hooks/accounts/useSigner.ts, packages/react/src/hooks/contracts/useContractEvent.ts, packages/react/src/hooks/contracts/useContractRead.ts, packages/react/src/hooks/contracts/useToken.ts, packages/react/src/hooks/ens/index.ts, packages/react/src/hooks/ens/useEnsAvatar.ts, packages/react/src/hooks/ens/useEnsLookup.test.ts, packages/react/src/hooks/ens/useEnsLookup.ts, packages/react/src/hooks/ens/useEnsResolveName.test.ts, packages/react/src/hooks/ens/useEnsResolveName.ts, packages/react/src/hooks/ens/useEnsResolver.ts, packages/react/src/hooks/index.ts, packages/react/src/hooks/network-status/useBlockNumber.ts, packages/react/src/hooks/network-status/useFeeData.ts, packages/react/src/hooks/transactions/useWaitForTransaction.ts, packages/react/src/index.test.ts, packages/react/src/index.ts
Added a `resolveName` hook to resolve ens to address
ref: https://docs.ens.domains/dapp-developer-guide/resolving-names
=> feat: ini ens resolveName

jest.config.js, packages/core/package.json, packages/core/src/actions/accounts/balance.test.ts, packages/core/src/actions/accounts/balance.ts, packages/core/src/actions/accounts/index.ts, packages/core/src/actions/index.ts, packages/core/src/constants/units.ts, packages/core/src/index.test.ts, packages/core/src/index.ts, packages/core/src/types/actions.ts, packages/core/src/types/index.ts, packages/core/test/index.ts, packages/core/test/setup.ts, packages/react/src/hooks/accounts/useBalance.test.ts, packages/react/src/hooks/accounts/useBalance.ts, packages/react/test/index.tsx, pnpm-lock.yaml
Starting to separate hook logic into core actions.
- https://github.com/tmm/wagmi/discussions/140
- #153
=> refactor: create actions

docs/pages/guides/sign-message.mdx
=> Typo in wagmi/guides/sign-message

docs/pages/docs/hooks/useContractWrite.mdx
=> Added an example of how to use the callback as an action

.changeset/proud-brooms-agree.md, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
This is most notably to fix this issue: https://github.com/WalletConnect/walletconnect-monorepo/issues/718
=> fix: update WalletConnect ethereum-provider to v1.7.4

.changeset/brave-mugs-deny.md, docs/pages/docs/hooks/meta.json, docs/pages/docs/hooks/useSignTypedData.mdx, packages/react/src/hooks/accounts/useSignTypedData.test.ts, packages/react/src/hooks/accounts/useSignTypedData.ts
=> feat: useSignTypedData

rfcs/001-deterministic-states-and-caching.md
[See formatted](https://github.com/jxom/wagmi-1/blob/ad88f59d4a3fed30e5f2b7a5d8c58cc0132dd62d/rfcs/001-deterministic-states-and-caching.md)
=> rfc: Deterministic states & caching

docs/pages/guides/sign-in-with-ethereum.mdx
**Summary:**
Adjusted docs to mention iron-session types that are needed
**BREAKING CHANGE:** 🧨 n
**Your ENS/address:**
`codingwithmanny.eth`
=> docs: ✏️ Added iron-session types

docs/pages/docs/connectors/coinbase-wallet.en-US.mdx
=> docs: fix Coinbase Wallet SDK docs links

.changeset/tough-cups-provide.md, babel.config.js
- build: change babel target
- chore: changeset
=> build: change babel target

packages/react/src/hooks/transactions/useWaitForTransaction.ts
=> useWaitForTransaction: require hash or wait parameter, not both

docs/pages/docs/constants/rpcs.en-US.mdx
Your ENS/address: thatguyintech.eth
=> add more example rpc url chains

.changeset/twelve-kings-wash.md, packages/core/src/constants/chains.ts
The PR includes support for Gnosis Chain.
=> Add gnosis chain configuration

docs/pages/docs/hooks/useToken.mdx
Your ENS/address: `qdqd.sismo.eth`
=> docs: useToken page -- fix imports

examples/next/src/pages/_app.tsx, packages/core/connectors/coinbaseWallet/package.json, packages/core/package.json, packages/core/src/connectors/coinbaseWallet.ts, packages/react/connectors/coinbaseWallet/package.json, packages/react/package.json, packages/react/src/connectors/coinbaseWallet.ts, pnpm-lock.yaml
Change: walletlink is deprecated. Added coinbase-wallet-sdk.
=> Update coinbase wallet sdk

packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
related: https://github.com/tmm/wagmi/pull/347/files
=> Update @coinbase/wallet-sdk to 3.0.8

packages/react/package.json, packages/react/src/utils/deserialize.ts, pnpm-lock.yaml
=> chore: bump react-query

docs/pages/docs/hooks/useEnsAddress.en-US.mdx, docs/pages/docs/hooks/useEnsAvatar.en-US.mdx, docs/pages/docs/hooks/useEnsName.en-US.mdx, docs/pages/docs/hooks/useEnsResolver.en-US.mdx, docs/pages/docs/hooks/useToken.en-US.mdx, packages/react/src/context.tsx, packages/react/src/hooks/contracts/useToken.ts, packages/react/src/hooks/ens/useEnsAddress.ts, packages/react/src/hooks/ens/useEnsAvatar.ts, packages/react/src/hooks/ens/useEnsName.ts, packages/react/src/hooks/ens/useEnsResolver.ts
Times were not scaled correctly to milliseconds.
=> fix: time scale

package.json, packages/react/package.json, packages/react/src/hooks/utils/useQuery.ts, pnpm-lock.yaml
https://github.com/tannerlinsley/react-query/pull/3561
=> refactor: use fully-specified path for use-sync-external-store import

README.md, docs/pages/index.en-US.mdx
=> docs: fix connect examples

packages/core/src/actions/contracts/getContract.ts, packages/core/src/actions/contracts/watchReadContract.ts, packages/core/src/client.test.ts, packages/core/src/connectors/base.ts, packages/core/src/connectors/coinbaseWallet.ts, packages/core/src/connectors/injected.ts, packages/react/src/hooks/contracts/useContract.test.ts, packages/react/src/index.test.ts, packages/react/src/index.ts, packages/react/src/utils/deserialize.test.ts, packages/react/src/utils/serialize.test.ts, packages/react/src/utils/serialize.ts
More stable, faster `serialize`
=> refactor: serialize

packages/core/test/utils.ts, packages/react/src/hooks/contracts/useContractRead.ts
=> fix: add missing param to contract read

package.json
fixed hardhat dev script so you can run using installed hardhat 
bolau.eth
=> chore: fixed hardhat dev script

docs/pages/docs/migrating-to-03.en-US.mdx
Use new hook name in after example.
- [ x] I read the contributing docs (if this is your first contribution)
Your ENS/address: timoclasen.eth
=> Fix Hook Name in After Example

README.md, docs/components/core/Providers.tsx, docs/pages/docs/comparison.en-US.mdx, docs/pages/docs/connectors/injected.en-US.mdx, docs/pages/docs/connectors/meta.en-US.json, docs/pages/docs/connectors/metamask.en-US.mdx, docs/pages/examples/connect-wallet.en-US.mdx, docs/pages/index.en-US.mdx, examples/_dev/src/pages/_app.tsx, examples/cra/src/index.tsx, examples/next/src/pages/_app.tsx, examples/remix/app/root.tsx, examples/vite-react/src/App.tsx, examples/vite-react/src/main.tsx, packages/core/connectors/metaMask/package.json, packages/core/package.json, packages/core/src/connectors/coinbaseWallet.ts, packages/core/src/connectors/injected.ts, packages/core/src/connectors/metaMask.test.ts, packages/core/src/connectors/metaMask.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts, packages/react/connectors/metaMask/package.json, packages/react/package.json, packages/react/src/connectors/metaMask.ts, pnpm-lock.yaml
- Adds a MetaMask-specific connector (s/o @adbario for kicking off #279)
- Adds optional `name` configuration option to `InjectedConnector`
```ts
new InjectedConnector({ options: { name: 'Injected' }})
```
-  Decouple `CoinbaseWalletConnector` `ready` from `InjectedConnector`
=> feat: MetaMaskConnector

packages/react/src/hooks/index.ts, packages/react/src/index.test.ts, packages/react/src/index.ts
Exporting `useQuery` for consumers to use as an escape hatch. [See more.](https://github.com/tmm/wagmi/discussions/399)
=> feat: export `useQuery`

packages/core/src/connectors/walletConnect.ts
Adds MetaMask to programmatic switch chain allowlist for WalletConnectConnector
=> feat: add MetaMask to WalletConnectConnector switch chain allowlist

packages/core/src/connectors/walletConnect.ts
`imToken` already support switchChain
references:
- <https://imtoken.gitbook.io/developers/products/webview/rpcs#wallet_addethereumchain>
- <https://imtoken.gitbook.io/developers/products/webview/rpcs#wallet_switchethereumchain>
Your ENS/address: izayl.eth
=> feat(core): wc add `imToken` switchChain support

docs/pages/examples/custom-connector.en-US.mdx, docs/pages/examples/meta.en-US.json, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.ts
Added example for creating a custom connector.
=> docs: custom connector

packages/core/src/connectors/injected.ts, packages/core/src/errors.ts, packages/core/src/index.test.ts, packages/core/src/index.ts, packages/react/src/index.test.ts, packages/react/src/index.ts
Adds `ResourceUnavailableError`
=> feat: add unavailable rpc error

.changeset/config.json, .changeset/tender-coats-exercise.md, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
=> chore: bump dependencies

.changeset/thick-candles-repeat.md, packages/core/src/connectors/coinbaseWallet.ts
Add a workaround to fix #383
Working example vite app
cesargdm.eth
=> Workaround for CoinbaseWalletSDK default access

docs/pages/examples/sign-in-with-ethereum.en-US.mdx
Update the way to get the chain id in [Sign-In with Ethereum example](https://wagmi.sh/examples/sign-in-with-ethereum#step-3-sign--verify-message) 
=> docs: get chain id from activeChain by useNetwork

docs/pages/docs/providers/configuring-chains.en-US.mdx
- Fixes docs example to import `createClient`
worm.eth
=> Add createClient to setup example code

.changeset/forty-tools-behave.md, packages/core/src/actions/network-status/fetchFeeData.test.ts, packages/core/src/actions/network-status/fetchFeeData.ts
Fixes https://github.com/tmm/wagmi/issues/522
=> fix: fee data formatting

.changeset/cold-seals-lie.md, packages/core/package.json, packages/core/src/connectors/coinbaseWallet.ts, packages/react/package.json, pnpm-lock.yaml
Fix potential type error on connect for Coinbase Wallet.
=> fix: coinbase wallet connect

.changeset/dirty-shirts-clap.md, docs/pages/docs/constants/chains.en-US.mdx, packages/core/src/chains.ts, packages/core/src/constants/chains.ts, packages/react/src/chains.ts
Adds chain for [Foundry Anvil](https://github.com/foundry-rs/foundry/tree/master/anvil).
=> feat: add foundry chain

packages/core/src/actions/contracts/readContract.ts
=> Add missing word in error message

packages/core/src/connectors/metaMask.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
https://github.com/tmm/wagmi/pull/600
=> feat(injected): add TokenPocket

.changeset/stale-ghosts-develop.md, packages/core/src/types/index.ts, packages/core/src/utils/configureChains.ts
=> fix: fix broken `WebSocketProvider` type defs

docs/pages/docs/hooks/useSwitchNetwork.en-US.mdx
=> docs(useSwitchNetwork): fix imported hook

docs/pages/examples/sign-message.en-US.mdx
The code shown in the example pages is out date and doesn't work with simple copy & paste
0x8980dbbe60d92b53b08ff95ea1aaaabb7f665bcb
=> Fix example doesnt work

.changeset/healthy-ties-visit.md, packages/react/src/hooks/contracts/useContractRead.ts
=> fix: undefined query data

.changeset/fluffy-mayflies-watch.md, .changeset/happy-queens-laugh.md, .changeset/silent-pets-buy.md, docs/pages/docs/hooks/useToken.en-US.mdx, packages/core/src/actions/accounts/connect.ts, packages/core/src/actions/tokens/fetchToken.test.ts, packages/core/src/actions/tokens/fetchToken.ts, packages/core/src/client.ts, packages/core/src/connectors/index.ts, packages/core/src/connectors/injected.ts, packages/core/src/connectors/metaMask.ts, packages/core/src/constants/chains.ts, packages/core/src/index.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.ts, packages/react/src/hooks/contracts/useToken.test.ts, tsconfig.json
- Stay connected to existing connector when connect action fails
- Make chains arrays tree shakeable
- Make injected connector name override work with SSR
- Fix client auto connect loading status
- Add name to fetch token and refactor to use multicall
=> refactor: clean up

.changeset/smooth-pandas-kiss.md, docs/pages/docs/providers/alchemy.en-US.mdx, docs/pages/docs/providers/configuring-chains.en-US.mdx, docs/pages/docs/providers/infura.en-US.mdx, docs/pages/docs/providers/jsonRpc.en-US.mdx, docs/pages/docs/providers/public.en-US.mdx, packages/core/src/providers/alchemy.ts, packages/core/src/providers/infura.ts, packages/core/src/providers/jsonRpc.ts, packages/core/src/providers/public.ts, packages/core/src/utils/configureChains.test.ts, packages/core/src/utils/configureChains.ts
Remerge https://github.com/tmm/wagmi/pull/722
=> chore: remerge #722

.changeset/big-coins-attack.md, packages/react/connectors/mock/package.json, packages/react/package.json, packages/react/src/connectors/mock.ts
=> feat: add mock connector entrypoint

packages/core/src/actions/providers/getWebSocketProvider.test.ts, packages/core/test/utils.ts, packages/react/src/hooks/providers/useWebSocketProvider.test.ts
=> test: clean up websockets

README.md, packages/core/README.md, packages/react/README.md
😄 since i post a lot about wagmi
=> chore: plug me

.changeset/happy-starfishes-tell.md, packages/core/src/chains.ts, packages/core/src/constants/blockExplorers.ts, packages/core/src/constants/chains.ts, packages/core/src/constants/rpcs.ts, packages/react/src/chains.test.ts, packages/react/src/chains.ts
Adding Optimism Goerli as a supported chain
Your ENS/address: kerls.eth
=> add Optimism Goerli chain

.changeset/orange-eyes-press.md, packages/core/src/constants/chains.ts
=> fix: add optimism goerli to chain lookup

README.md, docs/components/docs/Sponsors.tsx, docs/components/docs/index.ts, docs/pages/examples/connect-wallet.en-US.mdx, docs/pages/index.en-US.mdx
=> chore: add sponsor

.changeset/silly-numbers-try.md, packages/react/package.json, packages/react/src/client.ts, packages/react/src/context.tsx, packages/react/src/hooks/accounts/useConnect.ts, packages/react/src/hooks/accounts/useDisconnect.ts, packages/react/src/hooks/accounts/useSignMessage.ts, packages/react/src/hooks/accounts/useSignTypedData.ts, packages/react/src/hooks/accounts/useSigner.ts, packages/react/src/hooks/accounts/useSwitchNetwork.ts, packages/react/src/hooks/contracts/useContractRead.ts, packages/react/src/hooks/contracts/useContractReads.ts, packages/react/src/hooks/contracts/useContractWrite.ts, packages/react/src/hooks/contracts/useDeprecatedContractWrite.ts, packages/react/src/hooks/contracts/usePrepareContractWrite.ts, packages/react/src/hooks/network-status/useBlockNumber.ts, packages/react/src/hooks/transactions/useDeprecatedSendTransaction.ts, packages/react/src/hooks/transactions/useSendTransaction.ts, packages/react/src/hooks/utils/query/useBaseQuery.ts, packages/react/src/hooks/utils/query/useInfiniteQuery.ts, packages/react/src/hooks/utils/query/useQuery.ts, packages/react/src/hooks/utils/query/utils.ts, packages/react/src/hooks/utils/useInvalidateOnBlock.ts, packages/react/src/types/index.ts, packages/react/src/utils/deserialize.ts, packages/react/test/index.tsx, pnpm-lock.yaml
Updating to React Query 4 stable!
=> chore: update to React Query 4 stable

.changeset/silent-numbers-learn.md, packages/core/package.json, packages/core/src/client.ts, packages/react/src/context.test.ts, pnpm-lock.yaml
=> chore: update zustand

docs/pages/docs/connectors/coinbaseWallet.en-US.mdx
fixed import typo
Your ENS/address: ayushp.eth
=> fix typo in import

packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
Add MathWallet types and names
mathwallet.eth
=> add MathWallet

.changeset/heavy-geckos-smell.md, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
=> chore: add BitKeep

docs/pages/docs/hooks/useWaitForTransaction.en-US.mdx
Just fixing typos :).
Your ENS/address: enriqueop.eth
=> Fix: `usePrepareContractWrited` -> `usePrepareContractWrite`

.changeset/serious-moons-design.md, packages/core/src/connectors/base.ts
Fixes https://github.com/wagmi-dev/wagmi/issues/969
=> fix: add decimals to watchAsset

.changeset/many-baboons-brake.md, packages/core/src/actions/network-status/watchBlockNumber.test.ts, packages/core/src/actions/network-status/watchBlockNumber.ts
This PR fixes an issue where `watchBlockNumber` was not chain aware, as well as fixing listener instances.
=> fix: make `watchBlockNumber` chain aware + fix listener

packages/core/src/actions/network-status/watchBlockNumber.ts
Follow up for #1008. There were a couple of cases where `watchBlockNumber` did not unsubscribe – this PR ensures that the subscription is cut when the signer disconnects & ensures that the subscription does not emit events after the subscription is released.
=> fix: ensure `watchBlockNumber` unsubscribes correctly

examples/next/src/pages/index.tsx
Fixes https://github.com/wagmi-dev/wagmi/issues/542#issuecomment-1267771796
=> fix: apply SSR workaround for Next.js example

.changeset/fluffy-worms-sip.md, .changeset/tricky-kids-end.md, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
=> chore: update dependencies

docs/pages/docs/prepare-hooks/usePrepareContractWrite.en-US.mdx, docs/pages/examples/custom-connector.en-US.mdx, packages/core/src/utils/parseContractResult.test.ts
Just fixing a minor typos in the docs.
=> Fix `adddress` Typo

.changeset/warm-experts-beam.md, package.json, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
=> chore: bump abitype

packages/core/src/actions/accounts/fetchBalance.ts, packages/core/src/actions/accounts/signMessage.ts, packages/core/src/actions/accounts/signTypedData.ts, packages/core/src/actions/accounts/switchNetwork.ts, packages/core/src/actions/contracts/fetchToken.test.ts, packages/core/src/actions/contracts/getContract.ts, packages/core/src/actions/ens/fetchEnsAddress.ts, packages/core/src/actions/ens/fetchEnsName.ts, packages/core/src/actions/network-status/fetchFeeData.ts, packages/core/src/actions/transactions/fetchTransaction.ts, packages/core/src/actions/transactions/sendTransaction.test.ts, packages/core/src/actions/transactions/sendTransaction.ts, packages/core/src/actions/transactions/waitForTransaction.ts, packages/core/src/connectors/coinbaseWallet.ts, packages/core/src/connectors/injected.ts, packages/core/src/connectors/metaMask.ts, packages/core/src/connectors/mock/connector.ts, packages/core/src/connectors/walletConnect.ts, packages/core/src/storage.ts, packages/core/src/utils/configureChains.ts, packages/core/src/utils/minimizeContractInterface.ts, packages/core/src/utils/parseContractResult.ts, packages/core/test/utils.ts, packages/react/src/hooks/accounts/useConnect.ts, packages/react/src/hooks/accounts/useSignMessage.ts, packages/react/src/hooks/accounts/useSwitchNetwork.ts, packages/react/test/setup.ts
`as` more readable than bracket syntax. swapping things over.
=> refactor: type casts

.changeset/odd-dingos-tease.md, .changeset/young-dancers-joke.md, packages/core/src/actions/contracts/getContract.ts, packages/core/src/actions/contracts/watchContractEvent.ts, packages/core/src/index.ts, packages/core/src/internal.ts, packages/core/src/types/contracts.ts, packages/react/src/hooks/contracts/useContractEvent.ts, packages/react/src/hooks/contracts/useContractInfiniteReads.ts, packages/react/src/hooks/contracts/useContractReads.ts, packages/react/src/hooks/utils/index.ts, packages/react/src/hooks/utils/query/index.ts, packages/react/src/hooks/utils/query/useInfiniteQuery.ts
=> fix: TypeScript-related issues

.changeset/dirty-bananas-kneel.md, .changeset/rich-months-hide.md, .changeset/spotty-points-tan.md, docs/pages/docs/constants/abis.en-US.mdx, packages/core/src/constants/abis.ts, packages/core/src/constants/index.ts, packages/core/src/index.ts, packages/react/src/index.ts
This PR adds erc4626 ABI for easy integration of the [tokenized vault standard](https://ethereum.org/en/developers/docs/standards/tokens/erc-4626)
Your ENS/address: toniocodo.eth
=> Add erc4626ABI support

.changeset/fast-brooms-join.md, packages/core/src/connectors/base.ts
=> fix: add chain without block explorer

.changeset/chilled-dogs-shake.md, packages/core/src/connectors/metaMask.ts, packages/core/src/connectors/walletConnect.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
Adds support for Trust Wallet browser extension.
=> feat: add support for trust wallet browser extension

docs/pages/docs/hooks/useContractInfiniteReads.en-US.mdx
Change contractConfig -> mlootContractConfig
=> change: mlootContractConfig var

.changeset/wicked-ladybugs-raise.md, packages/core/src/actions/ens/fetchEnsName.ts
=> fix: ethers import path

.changeset/gold-lies-crash.md, packages/core/src/internal.ts, packages/core/src/types/contracts.ts
=> fix: internal type

docs/pages/examples/sign-in-with-ethereum.en-US.mdx
Updated SIWE example docs with updated useNetwork functionality
BREAKING CHANGE: n
Closes: 1336
codingwithmanny.eth
=> docs: SIWE docs useNetwork Fix

.changeset/giant-tools-do.md, packages/core/package.json, pnpm-lock.yaml
Upgrade @coinbase/wallet-sdk to the newest version. v3.6.0. [changelog](https://github.com/coinbase/coinbase-wallet-sdk/releases/tag/v3.6.0)
=> upgrade coinbase wallet sdk

packages/core/package.json, packages/react/package.json
adding core team (+ emails) to packages 🤝
=> chore: add core team as contributors

.changeset/three-mirrors-begin.md, docs/pages/react/hooks/useEnsResolver.en-US.mdx, docs/pages/react/migration-guide.en-US.mdx, packages/react/src/hooks/ens/useEnsResolver.ts
Remove persistence from `useEnsResolver`'s result
=> fix(react): do not persist `useEnsResolver` result

docs/pages/examples/send-transaction.en-US.mdx
Updated send transaction documentation with adjusted variable names
BREAKING CHANGE: N
Updated `send-transaction.en-US.mdx` with adjusted variables for devs to copy and paste.
codingwithmanny.eth
=> docs: send-transaction.en-US.mdx

.changeset/healthy-windows-switch.md, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml, tsconfig.json
Bumping [ABIType](https://github.com/wagmi-dev/abitype) version. No breaking changes.
=> chore: update abitype version

docs/pages/core/actions/watchContractEvent.en-US.mdx
=> docs: update watchContractEvent docs

docs/pages/core/connectors/injected.en-US.mdx, docs/pages/react/connectors/injected.en-US.mdx
=> docs: fix `InjectedConnector` imports

pnpm-lock.yaml
Updating `references` submodule for `@wagmi/connectors@0.1.1`
=> chore: update `references` submodule

.github/workflows/main.yml
Cache Anvil RPC data across runs to speed things up.
s/o https://twitter.com/paulrberg/status/1603057723985301507
=> ci: cache anvil rpc data

.changeset/dull-apes-march.md, packages/core/src/chains.test.ts, packages/core/src/chains.ts, packages/react/src/chains.test.ts, packages/react/src/chains.ts
Updating `@wagmi/chains` for `bscTestnet` RPC URL fix & Taraxa.
=> chore: update `@wagmi/chains`

packages/core/.gitignore, packages/core/package.json, packages/core/tsup.config.ts, packages/react/.gitignore, packages/react/package.json, packages/react/tsup.config.ts, scripts/tsup.ts
Generate package.json exports from entry instead of manually updating it.
=> build: generate package.json exports

docs/pages/react/connectors/injected.en-US.mdx
Refer to `references` repo when linking to `getInjectedName.ts` file
Your ENS/address: mihirg.eth
=> fix(injected.en-US.mdx): fixes broken link

.changeset/tricky-plums-switch.md, docs/pages/core/chains.en-US.mdx, docs/pages/react/chains.en-US.mdx, packages/core/src/chains.test.ts, packages/core/src/chains.ts, packages/react/src/chains.test.ts, packages/react/src/chains.ts
Updating `references/` submodule.
=> chore: update references

docs/pages/react/connectors/injected.en-US.mdx
fix docs has no exported member
=> fix docs has no exported member

.changeset/selfish-balloons-live.md, scripts/cjs.ts
=> fix: cjs dependency version range

packages/core/package.json, packages/core/src/client.ts, pnpm-lock.yaml
Fix zustand `getStorage` deprecation warning.
peterferguson.eth
=> fix: remove zustand deprecation warning (#1634)

.changeset/nine-walls-explode.md, packages/react/src/index.ts
Exporting internal type. Nothing to see here.
=> chore: export internal type

.github/workflows/main.yml, packages/react/src/hooks/accounts/useSignTypedData.ts, packages/react/src/hooks/contracts/useContractWrite.ts, pnpm-lock.yaml
Amending the lint action to apply fixes.
=> ci: amend lint action to apply & commit fixes

docs/pages/react/_meta.zh-CN.json, docs/pages/react/comparison.zh-CN.mdx
Translate a single page. It belongs to  #1582
Your ENS/address: 0x7E480e349a31F71f59B57cb30Bd850b4D643D617
=> 📃 docs(cn): translate docs/pages/react/comparison.en-US.mdx to zh-CN

.changeset/khaki-days-trade.md, .changeset/ten-frogs-report.md, packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/actions/accounts/getNetwork.test.ts, packages/core/src/actions/accounts/getNetwork.ts, packages/core/src/actions/accounts/switchNetwork.test.ts, packages/core/src/actions/accounts/watchNetwork.test.ts, packages/core/src/utils/configureChains.test.ts, packages/react/CHANGELOG.md, packages/react/package.json, packages/react/src/hooks/accounts/useSwitchNetwork.test.ts, pnpm-lock.yaml, scripts/tsup.ts
Update references
Closes #1664
=> chore: bump references

docs/pages/react/_meta.zh-CN.json, docs/pages/react/providers/_meta.zh-CN.json, docs/pages/react/providers/alchemy.zh-CN.mdx, docs/pages/react/providers/configuring-chains.zh-CN.mdx, docs/pages/react/providers/infura.zh-CN.mdx, docs/pages/react/providers/jsonRpc.zh-CN.mdx, docs/pages/react/providers/public.zh-CN.mdx
Translate a single chapter. It belongs to https://github.com/wagmi-dev/wagmi/discussions/1582
Your ENS/address: 0x7E480e349a31F71f59B57cb30Bd850b4D643D617
=> 📃 docs(cn): translate docs/pages/react/providers to zh-CN

.changeset/thirty-garlics-divide.md, docs/pages/core/connectors/_meta.en-US.json, docs/pages/core/connectors/safe.en-US.mdx, docs/pages/react/connectors/_meta.en-US.json, docs/pages/react/connectors/safe.en-US.mdx, examples/_dev/next.config.js, examples/_dev/public/manifest.json, examples/_dev/src/pages/_app.tsx, examples/_dev/wagmi.config.ts, packages/core/.gitignore, packages/core/package.json, packages/core/src/connectors/safe.ts, packages/core/tsup.config.ts, packages/react/.gitignore, packages/react/package.json, packages/react/src/connectors/safe.ts, packages/react/tsup.config.ts, pnpm-lock.yaml
=> feat: SafeConnector

docs/pages/cli/configuration/options.en-US.mdx
=> Fixed commas

docs/pages/react/hooks/useConnect.en-US.mdx
Updated the return value in the useConnect docs. `address` -> `account`.
Your ENS/address: N/A
=> chore: update return value of useConnect in docs

docs/pages/core/providers/configuring-chains.en-US.mdx, docs/pages/react/providers/configuring-chains.zh-CN.mdx
=> fix: fix doc core/react providers link bug

.changeset/sweet-paws-shave.md, packages/cli/package.json, packages/cli/src/commands/generate.ts, pnpm-lock.yaml, scripts/cjs.ts
Switches from `@ethersproject/address` `getAddress` to `viem` `getAddress`.
=> refactor: use viem utils in cli

.changeset/hot-months-cross.md, packages/cli/src/plugins/__snapshots__/actions.test.ts.snap, packages/cli/src/plugins/__snapshots__/react.test.ts.snap, packages/cli/src/plugins/actions.test.ts, packages/cli/src/plugins/actions.ts, packages/cli/src/plugins/react.test.ts, packages/cli/src/plugins/react.ts
Checks to make sure generated hook name is not already used.
Closes #1999
=> fix(cli): react plugin name conflict

docs/pages/examples/connect-wallet.en-US.mdx
Now that Dynamic is in public release and offers a free wallet library/adapter, I added it as a reference option in the examples.
- Full wagmi/dynamic guide is available here: https://docs.dynamic.xyz/docs/wagmi-v2
=> Added Dynamic as one of the connector options

.changeset/mighty-kiwis-boil.md
Fixes https://github.com/wagmi-dev/wagmi/issues/1942
=> fix: switch chain after add

.changeset/unlucky-walls-suffer.md, packages/core/src/actions/contracts/multicall.test.ts, packages/core/src/actions/contracts/multicall.ts, packages/core/src/errors.ts
=> fix: throw if chain not configured on client for multicall

.changeset/hip-hats-attack.md, packages/react/package.json, packages/react/src/context.test.ts, pnpm-lock.yaml
=> chore: bump react-query & abitype

.changeset/poor-rice-jam.md, packages/cli/src/plugins/hardhat.ts, packages/cli/src/utils/packages.ts
=> fix: hardhat plugin npm exec

docs/pages/cli/create-wagmi.en-US.mdx
=> Update template descriptions in create-wagmi docs

docs/pages/react/hooks/useSendTransaction.en-US.mdx
updated the function argument as per type `SendTransactionPreparedRequest`
Your ENS/address: 0xEd8f13964A38B7ea76De161742CaE9bD5f35aBF3
=> docs: updated useSendTransaction.en-US.mdx

.changeset/gorgeous-emus-camp.md, docs/package.json, examples/_dev/package.json, package.json, packages/cli/package.json, packages/cli/vhs/package.json, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml, tsconfig.json
https://github.com/wagmi-dev/references/pull/307
=> fix: abitype build

.changeset/afraid-dolphins-mix.md, packages/react/src/hooks/utils/useInvalidateOnBlock.ts
Fixes https://github.com/wagmi-dev/wagmi/issues/2442
=> Fix useInvalidateOnBlock invalidateQueries

.changeset/quiet-dragons-warn.md, .changeset/tame-badgers-brush.md, docs/pages/core/chains.en-US.mdx, docs/pages/react/chains.en-US.mdx, package.json, packages/cli/package.json, packages/core/package.json, packages/core/src/chains.test.ts, packages/core/src/chains.ts, packages/react/package.json, packages/react/src/chains.test.ts, packages/react/src/chains.ts, pnpm-lock.yaml
Updated references + abitype to 0.8.7
=> chore: update references + abitype

docs/pages/react/config.en-US.mdx
Fix documentation of `Config` in `wagmi/react`
[link](https://wagmi.sh/react/config#usage)
=> fix(doc): wrong argument

docs/pages/core/_meta.en-US.json, docs/pages/core/ethers-adapters.en-US.mdx, docs/pages/react/_meta.en-US.json, docs/pages/react/_meta.zh-CN.json, docs/pages/react/ethers-adapters.en-US.mdx
=> docs: ethers adapters reference implementation

.changeset/tidy-dodos-enjoy.md, packages/core/src/actions/contracts/writeContract.test.ts, packages/core/src/actions/contracts/writeContract.ts, packages/react/src/hooks/contracts/useContractWrite.ts
=> fix: `writeContract` parameter compat with `prepareWriteContract`

.changeset/wise-numbers-serve.md, packages/cli/src/plugins/etherscan.ts
Description
closes https://github.com/wagmi-dev/wagmi/issues/2551
Adds changeset to https://github.com/wagmi-dev/wagmi/pull/2561
Additional Information
I read the [contributing docs](https://github.com/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
=> fix: optimism goerli chainId

docs/pages/cli/plugins/react.en-US.mdx
Fix broken links in CLI docs.
Your ENS/address: alexgrover.eth
=> docs: fix broken links

docs/pages/core/providers/configuring-chains.en-US.mdx, docs/pages/react/providers/configuring-chains.en-US.mdx
Fixed typo in RPC providers docs
Your ENS/address: schlabach.eth
=> docs: fix typo in RPC Providers docs

.changeset/soft-kiwis-deliver.md, packages/cli/package.json, packages/cli/src/utils/resolveConfig.ts
Fixes https://github.com/wagmi-dev/wagmi/issues/2254
=> chore(cli): upgrade esbuild version

.changeset/kind-icons-tap.md, packages/cli/package.json
=> fix: cli esbuild version

.changeset/clean-gifts-flow.md, packages/connectors/src/metaMask.ts, packages/connectors/src/types.ts, packages/connectors/src/utils/getInjectedName.test.ts, packages/connectors/src/utils/getInjectedName.ts
Adds 'knowledge' about Zeal wallet.
Your ENS/address: 0x61640A8D48Bca205BA91b16B0B7745e7aBc61084
=> Add Zeal wallet

.changeset/hungry-bobcats-lick.md, packages/connectors/package.json, pnpm-lock.yaml
- Update `@walletconnect/ethereum-provider` and `@walletconnect/modal` dependencies
Your ENS/address: asimetriq.eth
=> Update WalletConnect dependencies

docs/.vitepress/sidebar.ts, docs/react/api/WagmiProvider.md, docs/react/api/connectors.md, docs/react/api/hooks.md, docs/react/api/hooks/useAccount.md, docs/react/api/hooks/useBalance.md, docs/react/api/hooks/useBlock.md, docs/react/api/hooks/useBlockNumber.md, docs/react/api/hooks/useChainId.md, docs/react/api/hooks/useConfig.md, docs/react/api/hooks/useConnect.md, docs/react/api/hooks/useConnections.md, docs/react/api/hooks/useDisconnect.md, docs/react/api/hooks/useEnsAddress.md, docs/react/api/hooks/useEnsAvatar.md, docs/react/api/hooks/useEnsName.md, docs/react/api/hooks/useEnsResolver.md, docs/react/api/hooks/useEstimateFeesPerGas.md, docs/react/api/hooks/useReconnect.md, docs/react/api/hooks/useSwitchAccount.md, docs/react/api/hooks/useToken.md, docs/react/getting-started.md, docs/shared/createConfig.md
=> docs: reorganize sidebar

.changeset/shaggy-ladybugs-prove.md, docs/pages/cli/plugins/foundry.en-US.mdx, packages/cli/src/plugins/foundry.ts
ignore foundry invariant lib (`StdInvariant` contract from `forge-std`).
https://github.com/foundry-rs/forge-std/blob/master/src/StdInvariant.sol
Your ENS/address: `cruzdanilo.eth`
=> cli: ignore foundry invariant lib

docs/pages/core/connectors/walletConnect.en-US.mdx, docs/pages/react/connectors/walletConnect.en-US.mdx, packages/connectors/src/walletConnect.ts
Updated WalletConnect Links in JSDoc comments & markdown
boidu.eth
=> Updated WalletConnect Links in JSDoc comments & markdown

.changeset/silly-pots-flow.md, packages/cli/src/utils/format.ts
Closes https://github.com/wagmi-dev/wagmi/issues/2971
=> Fix ESM require issue for prettier

.github/CONTRIBUTING.md
=> docs: update Anvil link

packages/core/src/config.ts
=> chore: fix a typo

docs/pages/examples/send-transaction.en-US.mdx
Improved code consistency by modifying the import and usage of the parseEther() function. Additionally, to prevent potential issues, added the type="button" attribute to the button element in the example.
=> docs: added type to button and update dependencies

.vscode/settings.json, packages/core/src/actions/disconnect.test.ts, packages/core/src/actions/disconnect.ts, packages/react/src/hooks/useConnect.ts, playgrounds/vite-react/src/App.tsx
=> fix: disconnect eagerly

.changeset/gentle-ways-agree.md, .changeset/selfish-jeans-teach.md, packages/connectors/src/walletConnect.ts
> [!NOTE]
> To be merged on December 7th
This PR removes required namespaces in WalletConnect session proposals
closes https://github.com/wevm/wagmi/issues/3027
=> Remove required namespaces from WalletConnect Connector Wagmi v1

.changeset/nervous-tigers-smash.md, packages/connectors/package.json, pnpm-lock.yaml
Fixed issue https://github.com/wevm/viem/issues/579 bumping `@safe-global/safe-apps-provider@0.18.1`.
Related issue https://github.com/safe-global/safe-apps-sdk/issues/480
=> Fixed Safe connector for contract writes

docs/shared/createConfig.md
Just some tiny documentation fixes for the new version coming out.
=> Fix 404s in createConfig docs

docs/react/getting-started.md
=> Fix doc link

docs/core/api/actions/multicall.md, docs/core/api/actions/readContract.md, docs/core/api/actions/readContracts.md, docs/core/api/actions/simulateContract.md, docs/core/api/actions/writeContract.md
=> Fix missing config argument

.changeset/fuzzy-scissors-smell.md, packages/react/src/hooks/useConnect.ts
=> fix: useConnect error getting unset

.changeset/rich-forks-enjoy.md, packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/metaMask.ts, packages/core/src/connectors/injected.ts, playgrounds/vite-react/src/wagmi.ts
=> fix: useConnect with chainId error bubbling

docs/react/guides/ssr.md
=> Fix ssr.md

.changeset/rough-scarves-dance.md, .changeset/smooth-pants-smoke.md, docs/.vitepress/sidebar.ts, docs/core/api/actions/call.md, docs/react/api/hooks/useCall.md, packages/core/src/actions/call.test.ts, packages/core/src/actions/call.ts, packages/core/src/exports/actions.test.ts, packages/core/src/exports/actions.ts, packages/core/src/exports/index.test.ts, packages/core/src/exports/index.ts, packages/core/src/exports/query.test.ts, packages/core/src/exports/query.ts, packages/core/src/query/call.test.ts, packages/core/src/query/call.ts, packages/react/src/exports/index.test.ts, packages/react/src/exports/index.ts, packages/react/src/exports/query.test.ts, packages/react/src/hooks/useCall.test-d.ts, packages/react/src/hooks/useCall.test.ts, packages/react/src/hooks/useCall.ts
- Adds the `call` core action and the `useCall` hook
=> Feat: add `call` and `useCall`

docs/react/guides/migrate-from-v1-to-v2.md
Make sure all effect dependencies are included.
=> docs: update migrate-from-v1-to-v2.md

.github/workflows/verify.yml, packages/test/src/globalSetup.ts
=> ci: fix open handles

docs/cli/api/plugins/fetch.md
It took me a while to copy and paste the path, delete it, and retry many times. Then I discovered this typo. 😢
=> fix(doc): wagmi cli cache location

.changeset/odd-waves-explode.md, packages/core/src/actions/readContracts.ts
Fixes https://github.com/wevm/wagmi/issues/3517
=> fix(core): multicall passthrough properties

docs/dev/contributing.md, playgrounds/next/src/wagmi.ts
=> chore: Remove wc id in next playground

.changeset/clean-bats-breathe.md, packages/core/src/actions/prepareTransactionRequest.test.ts, packages/core/src/actions/prepareTransactionRequest.ts, packages/core/src/actions/sendTransaction.test.ts, packages/core/src/actions/sendTransaction.ts, packages/core/src/actions/signMessage.test.ts, packages/core/src/actions/signMessage.ts, packages/core/src/actions/signTypedData.test.ts, packages/core/src/actions/signTypedData.ts, packages/core/src/actions/writeContract.ts, packages/react/src/hooks/useSignMessage.test.ts, packages/react/src/hooks/useSignTypedData.test.ts, packages/test/src/constants.ts, packages/test/src/exports/index.test.ts, packages/test/src/exports/index.ts
Closes https://github.com/wevm/wagmi/issues/3531
=> fix: account passthrough

.changeset/eight-jokes-report.md, packages/connectors/package.json, pnpm-lock.yaml
update `@walletconnect/ethereum-provider`
=> update @walletconnect/ethereum-provider wagmi V2

docs/shared/connectors/metaMask.md, packages/connectors/package.json, packages/connectors/src/metaMask.ts, pnpm-lock.yaml
Upgraded the `@metamask/sdk` package to version `0.14.3`, which resolves a bug as outlined in [issue #3400](https://github.com/wevm/wagmi/issues/3400). 
This update ensures smoother operation of MetaMask integration.
=> feat: update the '@metamask/sdk' package to version '0.14.3'

.changeset/big-weeks-hope.md, packages/core/src/createConfig.test.ts, packages/core/src/createConfig.ts
Fixes https://github.com/wevm/wagmi/issues/3485
Related https://github.com/wevm/wagmi/pull/3566
=> fix: getClient property passthrough

docs/react/guides/migrate-from-v1-to-v2.md
=> omit: queryClient missing

.changeset/bright-maps-stare.md, packages/connectors/src/coinbaseWallet.ts
=> fix: vite coinbase wallet import

docs/react/guides/migrate-from-v1-to-v2.md
One line fix adding a code removal/addition for the closure of the WagmiConfig/Provider
=> fix: Small typo fix in v2 migration docs

docs/react/guides/viem.md
=> fix(docs): typo in viem action usage

.changeset/sharp-fans-refuse.md, packages/cli/src/plugins/etherscan.ts
Added fraxtal etherscan documentation.
N/A
=> docs: fraxtal api url

docs/react/guides/ssr.md
```
const initialState = cookieToInitialState(config, headers().get("cookie"));
```
```
cookieToInitialState: State | undefined
```
=> Add undefined to Props.initialState

.changeset/good-boats-confess.md, packages/core/src/utils/getAction.ts
Fixing this Bug: https://github.com/wevm/wagmi/issues/3640
=> Fix: minification bug for Account Abstraction walletClients

.changeset/soft-coats-burn.md, packages/core/src/hydrate.ts
Fixes #3490
Fixes #3611
Closes #3683
Closes #3492
Added check to see if the store has not been hydrated yet before we set initial state.
=> fix: hydration check

.changeset/tiny-bees-own.md, packages/react/src/hooks/codegen/createUseWriteContract.ts
=> Add missing function name

.changeset/fuzzy-avocados-taste.md, packages/core/src/actions/disconnect.ts, packages/core/src/actions/reconnect.ts, packages/core/src/createConfig.test.ts, packages/core/src/createConfig.ts, packages/core/src/createStorage.test-d.ts, playgrounds/next/src/app/contracts.ts, playgrounds/next/src/app/page.tsx, playgrounds/next/src/wagmi.ts, playgrounds/next/tsconfig.json
=> fix: active chain when disconnected

.changeset/shaggy-boats-change.md, packages/core/src/connectors/injected.ts
=> fix: `shimDisconnect: false` behavior

.changeset/red-coats-think.md, .github/workflows/snapshot.yml, docs/core/api/actions/switchChain.md, docs/react/api/hooks/useSwitchChain.md, docs/shared/mutation-result.md, packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/metaMask.ts, packages/connectors/src/walletConnect.ts, packages/core/src/actions/switchChain.ts, packages/core/src/connectors/createConnector.ts, packages/core/src/connectors/injected.ts, packages/react/src/hooks/useSwitchChain.test-d.ts, packages/register-tests/react/src/useSwitchChain.test-d.ts
Adds `AddEthereumChainParameters` type to `Connector` `switchChain`, `@wagmi/core` `switchChain`, and `wagmi` `useSwitchChain`.
```ts
connector.switchChain?.({
chainId: 1,
addEthereumChainParameter: {
iconUrls: ['https://example.com/icon.png'],
},
})
```
```ts
import { switchChain } from '@wagmi/core'
switchChain(config, {
chainId: 1,
addEthereumChainParameter: {
iconUrls: ['https://example.com/icon.png'],
},
})
```
```ts
import { useSwitchChain } from 'wagmi'
const { switchChain } = useSwitchChain()
switchChain({
chainId: 1,
addEthereumChainParameter: {
iconUrls: ['https://example.com/icon.png'],
},
})
```
=> feat(connectors): switchChain AddEthereumChainParameters

.changeset/fresh-carrots-switch.md, packages/core/src/actions/waitForTransactionReceipt.ts
=> fix: use `data` property of return code

.changeset/loud-avocados-play.md, packages/core/src/actions/prepareTransactionRequest.test.ts, packages/core/src/actions/prepareTransactionRequest.ts, packages/react/src/hooks/usePrepareTransactionRequest.test.ts
=> fix: `prepareTransactionRequest` using unsupported wallet RPC methods.

.changeset/pink-spiders-approve.md, packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/metaMask.ts, packages/connectors/src/safe.ts, packages/connectors/src/walletConnect.ts
=> fix: make connector imports type-only

package.json, pnpm-lock.yaml
add vitest ui package
add `test:ui` command to package json which was referenced in contributing.md
screen shot when running command. Failing tests, assuming this is a known issue.
=> add vitest ui

.changeset/khaki-dingos-drive.md, packages/connectors/package.json, pnpm-lock.yaml
=> chore: update @metamask/sdk

site/.vitepress/config.ts, site/core/api/actions/getToken.md
- fix multicall link to viem,
- update "edit" link url
=> fix: update edit link and one viem ref link

.changeset/giant-insects-juggle.md, .changeset/late-fireants-turn.md, .github/CODEOWNERS, packages/connectors/package.json, packages/connectors/src/walletConnect.ts
=> feat: refactor `isChainsStale` in WalletConnect Connector

.changeset/tiny-countries-end.md, packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/metaMask.ts
=> fix: metamask connector for vite

site/react/guides/chain-properties.md
Very minor, fix wording in the docs.
=> Fix typo in chain properties section

.changeset/late-apes-yell.md, packages/connectors/src/walletConnect.ts
Related https://github.com/wevm/wagmi/pull/3978
=> fix(walletConnect): get chain ids

site/react/guides/viem.md
Fix the call of `useConnectorClient` hook in the guide "Leveraging Viem Actions" with React
=> doc: fix the call of `useConnectorClient` hook

.changeset/sweet-berries-invite.md, packages/connectors/src/metaMask.ts, packages/core/src/actions/reconnect.ts, playgrounds/vite-react/src/App.tsx, site/shared/connectors/metaMask.md
`metaMask` now supports mobile reconnection and uses deeplinks by default.
=> refactor(connectors): metaMask mobile reconnect

packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/metaMask.ts, packages/core/src/exports/internal.test.ts, packages/core/src/exports/internal.ts, packages/core/src/utils/loadDefault.ts
Adds internal import utility for Vite compatiblity
=> chore: vite import utility

site/core/guides/chain-properties.md, site/react/guides/chain-properties.md, site/shared/faq.md, site/vue/guides/chain-properties.md, site/vue/why.md
=> chore: fix some comments

.changeset/mean-kangaroos-drive.md, packages/cli/src/plugins/sourcify.ts
=> feat(sourcify): internal updates

site/core/why.md, site/react/guides/connect-wallet.md, site/react/why.md, site/vue/guides/connect-wallet.md, site/vue/why.md
Update AppKit branding and links.
=> Replace Web3Modal for AppKit

.changeset/neat-cups-rhyme.md, packages/core/src/connectors/injected.ts
=> Add withTimeout for wallet_revokePermissions request during disconnect

.changeset/smooth-suns-breathe.md, packages/connectors/package.json, packages/connectors/src/metaMask.ts, pnpm-lock.yaml
=> chore: update 'metamask-sdk' package to version '0.26.0'

playgrounds/next/src/app/page.tsx, playgrounds/vite-core/src/App.tsx, playgrounds/vite-react/src/App.tsx
The `balance?.formatted` is deprecated in favor of the newer one.
=> fix: deprecated `formatted`

.changeset/chatty-hotels-reply.md, packages/connectors/package.json, pnpm-lock.yaml
=> feat: update '@metamask/sdk' package to version '0.26.4'

.changeset/wet-peas-act.md, packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/metaMask.ts
Related https://github.com/wevm/wagmi/pull/4059
=> refactor(connectors): use named exports for async imports

site/vue/api/WagmiPlugin.md
Changes:
- replace `app.vue` with `main.ts`
=> Fix: code example in WagmiPlugin.md

.changeset/cold-roses-glow.md, packages/connectors/package.json, packages/connectors/src/safe.ts, pnpm-lock.yaml
=> chore: update `@safe-global/safe-apps-sdk`

site/react/guides/connect-wallet.md
=> Update AppKit guide link

site/react/guides/write-to-contract.md
Removed input boxes with input of Address and Value. Added input boxes with input of tokenId.
=> Fixed the wrong input boxes.

.changeset/nice-owls-smoke.md, packages/connectors/src/metaMask.ts
Related https://github.com/wevm/wagmi/pull/4203
=> fix: add name for mm connector

.changeset/slow-moose-unite.md, packages/connectors/package.json, pnpm-lock.yaml
- Updates `@walletconnect/ethehreum-provider` to version `2.15.3`
=> chore: update @walletconnect/ethehreum-provider to version 2.15.3

.changeset/ten-eggs-lie.md, packages/connectors/package.json, packages/connectors/src/metaMask.ts, pnpm-lock.yaml
Related https://github.com/wevm/wagmi/pull/4249
=> chore: bump mm sdk

.changeset/lazy-sloths-hunt.md, packages/vue/src/composables/useWatchContractEvent.test-d.ts, packages/vue/src/composables/useWatchContractEvent.test.ts, packages/vue/src/composables/useWatchContractEvent.ts, packages/vue/src/exports/index.test.ts, packages/vue/src/exports/index.ts, site/.vitepress/sidebar.ts, site/vue/api/composables/useWatchBlockNumber.md, site/vue/api/composables/useWatchContractEvent.md
Closes #4246 
Related https://github.com/wevm/wagmi/pull/4247
=> feat(vue): useWatchContractEvent

site/core/guides/chain-properties.md, site/core/guides/framework-adapters.md, site/core/guides/migrate-from-v1-to-v2.md, site/core/guides/viem.md, site/core/why.md
=> docs: fix typos

.changeset/three-singers-relate.md, packages/core/src/actions/getWalletClient.ts
=> chore: remove duplicate extend in getWalletClient

.changeset/odd-eyes-sip.md, packages/connectors/package.json, pnpm-lock.yaml
=> chore: bump mm

.changeset/tasty-clouds-kiss.md, packages/connectors/package.json, pnpm-lock.yaml
=> feat: bump metamask 0.30.0

.changeset/good-flowers-hunt.md, packages/core/package.json, packages/core/src/createConfig.ts, pnpm-lock.yaml
Bumps Zustand from v4 to v5
https://github.com/pmndrs/zustand/blob/main/docs/migrations/migrating-to-v5.md
=> chore(core): bump internal deps

.changeset/quick-pans-grow.md, .changeset/wild-guests-tell.md, packages/connectors/src/metaMask.ts, packages/core/src/connectors/createConnector.ts, packages/core/src/createConfig.test.ts, packages/core/src/createConfig.ts, packages/core/src/hydrate.ts
Related https://github.com/wevm/wagmi/pull/4405
Closes https://github.com/wevm/wagmi/issues/4404
=> feat: support multiple `rdns` to filter 6963 providers

site/shared/connectors/metaMask.md
This PR updates the doc page for the MetaMask SDK connector. This includes removing several options that we don't recommend configuring.
=> Update MetaMask connector doc

site/shared/connectors/metaMask.md
This PR improves the MetaMask connector functionality by implementing the following updates:
1. Enhanced Documentation:
- Added detailed explanations for advanced features such as headless mode, logging, and dappMetadata.
- Clarified the behavior of the connector when detecting an EIP-6963 MetaMask injected provider and how it is replaced to enhance functionality.
- Provided additional context about the rdns property and its role in uniquely identifying connectors.
2. Improved Configuration Options:
- Included headless mode support for custom modals, particularly useful in web-only setups using Wagmi.
- Highlighted the use of SDKLoggingOptions for debugging RPC methods and events.
3. Chain RPC Mapping:
- Improved documentation for configuring RPC transports, ensuring better developer …
=> Update MetaMask Connector documentation

.changeset/cyan-parents-rhyme.md, packages/react/package.json, pnpm-lock.yaml
Related https://github.com/wevm/wagmi/pull/4495
=> chore: bump uSES for React 19

.changeset/good-sheep-sparkle.md, packages/connectors/package.json, pnpm-lock.yaml
- Updated `@walletconnect/ethereum-provider` to `2.19.0`
=> chore: updated `ethereum-provider`

.changeset/nine-ways-push.md, packages/connectors/package.json, pnpm-lock.yaml
Updated `@walletconnect/ethereum-provider` to `2.19.1`
=> chore: updates EP to 2.19.1

site/react/why.md
Hi all! Quick commit to use possessive `its` instead of the contraction `it's`. If a PR this tiny doesn't make sense for other reasons, you're welcome to close it.
Thanks for all of your incredible work on wagmi!!
=> chore: fix typo

.changeset/silly-owls-nail.md, packages/connectors/package.json, pnpm-lock.yaml
=> feat: update `@walletconnect/ethereum-provider`

site/react/guides/connect-wallet.md
walletconnect is now reown
see: https://reown.com/blog/walletconnect-is-now-reown
=> docs: Update WalletConnect link in react connect-wallet guide

.changeset/green-walls-carry.md, packages/connectors/package.json, pnpm-lock.yaml
=> chore(connectors): updated `@walletconnect/ethereum-provider` to `2.20.2`

.changeset/violet-tables-shake.md, packages/connectors/package.json, pnpm-lock.yaml
- Updates `@walletconnect/ethereum-provider` to version 2.21.1
=> chore: updates @walletconnect/ethereum-provider to version 2.21.1

.github/workflows/changesets.yml, .github/workflows/issue-labeled.yml, .github/workflows/lock-issue.yml, .github/workflows/pull-request.yml, .github/workflows/verify.yml
=> ci: tune gh action permissions

site/react/getting-started.md, site/vue/getting-started.md
=> fix: tanstack query link

.changeset/long-moose-sniff.md, packages/cli/src/exports/plugins.test.ts, packages/cli/src/exports/plugins.ts, packages/cli/src/plugins/__snapshots__/routescan.test.ts.snap, packages/cli/src/plugins/blockExplorer.test.ts, packages/cli/src/plugins/fetch.test.ts, packages/cli/src/plugins/routescan.test.ts, packages/cli/src/plugins/routescan.ts, packages/cli/src/plugins/sourcify.ts, packages/cli/test/utils.ts, scripts/updateBlockExplorerPluginChains.ts, site/cli/api/plugins.md, site/cli/api/plugins/routescan.md
Adds [Routescan](https://routescan.io) CLI plugin
=> feat(cli): routescan plugin

.changeset/famous-windows-yawn.md, packages/connectors/package.json, playgrounds/next/src/wagmi.ts, playgrounds/nuxt/wagmi.ts, playgrounds/vite-core/src/wagmi.ts, playgrounds/vite-react/src/wagmi.ts, pnpm-lock.yaml, site/.vitepress/sidebar.ts, site/core/api/connectors/gemini.md, site/react/api/connectors/gemini.md, site/shared/connectors/gemini.md, site/vue/api/connectors/gemini.md
Add docs for gemini connector
Update @gemini-wallet/core to 0.2.0
=> doc: add gemini docs

.changeset/dry-pumas-happen.md, packages/core/src/createConfig.test.ts, packages/core/src/createConfig.ts
Adds internal `revalidate` function
Related https://github.com/wevm/wagmi/issues/4747
=> feat(core) add internal revalidate function
