packages/react/src/context.test.ts, packages/react/src/context.ts, packages/react/src/hooks/accounts/useAccount.ts, packages/react/src/hooks/accounts/useConnect.ts
Inspo #37 h/t @sammdec
When `Provider` `autoConnect={true}`, `useConnect` hook has `loading` set to `true` on load. After the auto connect process is tried, the global `connecting` value is switch back to `false`. (Maybe useful in the future to also set the global `connector` so you know what connector is attempting to auto connect.)
Decided to not make changes to `useAccount` loading because it isn't involved at this step of the "connection" process.
=> feat: autoconnect global loading

.changeset/fifty-emus-search.md, packages/react/src/index.test.ts, packages/react/src/index.ts
This PR exports the `Context`, so that it can be accessed directly by third party libs that need it for helpers.
For example, with [react-three-fiber](https://github.com/pmndrs/react-three-fiber), a react lib for creating 3d scenes, the [react context is lost inside the 3d scene.](https://docs.pmnd.rs/react-three-fiber/advanced/gotchas#consuming-context-from-a-foreign-provider), and you need to grab the context, and create a new provider within the 3d scene with that context.
For example, it would be great if you can do:
```jsx
import { useContextBridge } from "@react-three/drei"
import { Context as WagmiContext } from 'wagmi'
const SceneContainer = () => {
const ContextBridge = useContextBridge(WagmiContext)
return (
<Canvas>
<ContextBridge>
<Scene />
</ContextBridge>
</Canvas>
)
}
``` …
=> added context to the export

packages/private/src/connectors/injected.ts, packages/private/src/connectors/walletConnect.ts, packages/private/src/connectors/walletLink.ts, packages/testing/src/connectors/mockConnector.ts
On initial load of useAccount the address is checksummed but I noticed that after switching account in my wallet that the addresses returned were not, this PR fixes that by calling `getAddress` on the addresses returned from those events
=> Ensure addresses from accountsChanged events are checksummed

docs/pages/api/nonce.ts, docs/pages/api/verify.ts, docs/pages/guides/sign-in-with-ethereum.mdx, docs/types/iron-session.d.ts
Just noticed the nonce verification was missing in the Sign-in with Ethereum guide, just added the verification code from the [siwe-quickstart repo](https://github.com/spruceid/siwe-quickstart/blob/main/03_complete_app/backend/src/index.js#L21-L42).
Many thanks for this lib ✌🏻 
Your ENS/address: gomah.eth/0x561b5F3745a1a9e44Ac16010bd670eeAE0cA3379
=> docs: check the nonce during verification

.changeset/thin-wolves-joke.md, packages/private/src/connectors/injected.ts, packages/private/src/constants/chains.ts
MetaMask 10.9.3 emits disconnect event when chain is changed. https://github.com/MetaMask/metamask-extension/issues/13375#issuecomment-1027663334
This flag disables the disconnect event and relies on the accountsChanged event for updating wallet connection. This workaround is experimental and might result in stale connections.
=> feat: add shim for metamask chain change disconnect

docs/pages/guides/connectors.mdx
=> Typo in wagmi/guides/connectors

packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
Updates v6 with walletlink 2.5.0 which has support for [watch asset](https://github.com/coinbase/coinbase-wallet-sdk/pull/336) for custom tokens.
Your ENS/address: straightupjac.eth
=> fix: use walletlink 2.5.0 which has support for wallet_watchAsset

docs/pages/docs/provider.mdx
Your ENS/address: `ped.eth`
smol docs fix
=> docs: connector guide URL from provider docs

packages/react/src/index.ts
> Module '"wagmi"' has no exported member 'useWaitForTransaction'.
=> Export useWaitForTransaction

tsconfig.json
Safari doesn't support private class fields natively until 14.4. This means that anyone on iOS on a version less than that will have a broken experience. This changes the target output to use ES2021 this should transpile the minimum amount of features needed to have this still work in modern-ish browsers. In the interests of keeping Web3 accessible to folk who dont have the latest devices of OS's I think we should introduce a small amount of transpilation for a bigger support.
This fixes #288 
Your ENS/address: sammdec.eth
=> Use ES2021 as output for ESNext breaks some recent browsers

.changeset/big-dodos-ring.md, babel.config.js, tsconfig.json
Missed updating babel config when `wagmi-private` was renamed `wagmi-core`.
=> fix: private fields

packages/core/src/types/declarations.d.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
Adds the ability to detect if Brave Wallet is the currently injected web3 provider.
ENS/address: 0x46A628fF77afe9864dc8A4Fb34AB16f60F6733da
=> feat: add Brave Wallet detection

docs/pages/docs/hooks/useNetwork.mdx
`networkData` isn't defined, and so it throws and error. I assume it's not `networkData` but the `data` variable that you want to use.
Your ENS/address: 0xE4E6dC19efd564587C46dCa2ED787e45De17E7E1
=> Changed 'networkData' variable to 'data'

docs/pages/examples/sign-in-with-ethereum.en-US.mdx
This PR just fixes an incorrect usage of `useSignMessage` in the SIWE guide. I think it's still using the old API from `0.2.x`
Your ENS/address: dhaiwat.eth
=> docs: fix incorrect hook format in SIWE guide

packages/core/src/actions/contracts/readContract.ts, packages/react/src/hooks/contracts/useContractRead.ts
`signerOrProvider` is difficult to serialize and conflicts with other configuration, like `chainId`.
Fixes #367 
=> refactor: remove signerOrProvider option from read contract

docs/pages/docs/hooks/useConnect.en-US.mdx
Added option chainging to pendingConnector to do it possibly being null
Updated the docs based on TypeScript recommendation, made `pendingConnector.id` optional because it could potentially be null.
**Main change in docs:**
```diff
- pendingConnector.id
+ pendingConnector?.id
```
codingwithmanny.eth
=> docs: ✏️ Added optional chaining

docs/pages/examples/connect-wallet.en-US.mdx
Hi, guys. Your project looks awesome. When I started setting up connector configurations, I noticed that you left out the import in one of the examples.
```tsx
import { defaultChains } from 'wagmi';
```
=> Fix/missed import in the Connect wallet example

packages/core/src/connectors/injected.ts, packages/core/src/connectors/metaMask.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.ts
- Fixes https://github.com/tmm/wagmi/issues/434
- Adds better typing to `window.ethereum` wrapped RPC API
=> refactor: MetaMask and Brave Wallet collision

.changeset/tidy-elephants-drive.md, packages/core/src/client.ts
Fixes https://github.com/tmm/wagmi/issues/444 https://github.com/rainbow-me/rainbowkit/issues/347
=> fix: autoconnect with stale account

docs/pages/examples/sign-in-with-ethereum.en-US.mdx
Contrary of `useConnect`, `connectAsync` doesn't have an error or data field.
https://wagmi.sh/docs/hooks/useConnect#return-value
=> wrong connectAsync return data

packages/core/src/chains/configureChains.ts, packages/core/src/types/index.ts
Making the `defaultChains` type generic in `configureChains` as consumers may like to extend the `Chain` type (e.g. RainbowKit).
=> feat: make `defaultChains` type generic in `configureChains`

docs/pages/examples/connect-wallet.en-US.mdx
configureChains is called but wasn't imported.
=> Import configureChains from wagmi module

.changeset/eighty-baboons-provide.md, packages/core/src/connectors/walletConnect.ts
Wagmi now infers the `options.chainId` attribute on `WalletConnectConnector` to the first chain in the `chains` array that is passed to the connector.
Fixes https://github.com/tmm/wagmi/issues/516
=> fix: infer `chainId` config from `chains` on WalletConnectConnector

.changeset/empty-eyes-act.md, packages/react/package.json
Updating `react-query` to `4.0.0-beta.19` – this should fix issues we have been seeing around the `useSyncExternalStore` import.
=> chore: update react-query

docs/pages/docs/providers/configuring-chains.en-US.mdx
The custom Avalanche chain example was missing the `network` property, and the `blockExplorers` object was missing a value for `etherscan`.
=> docs: fix type errors in custom chain example

.changeset/hungry-ducks-compete.md, packages/core/src/constants/chains.ts, packages/core/src/providers/jsonRpc.ts, packages/core/src/types/index.ts
This PR enables the usage of custom ENS registry addresses with rainbowkit/wagmi. Ethers also supports [this](https://docs.ethers.io/v5/api/providers/types/#providers-Network). 
We have a private chain for testing purposes where we [deployed ENS contracts](https://docs.ens.domains/deploying-ens-on-a-private-chain). In order for our dApp (uses rainbowkit and wagmi) to work with this target environment, we would need this feature, so that we can configure the chains like:
```js
const { chains, provider } = configureChains(
[
{
name: 'private',
rpcUrls: {
default: 'https://private-rpc',
},
network: 'private',
id: 123456,
ensAddress: '0xCUSTOM_ENS_REGISTRY',
},
],
[
jsonRpcProvider({
rpc: (chain) => ({ http: chain.rpcUrls.default }),
}),
],
)
```
There might also be some cases where people …
=> feat: allow custom ens registry address

.changeset/slimy-boxes-happen.md, packages/react/src/hooks/ens/useEnsName.ts
`useEnsName`s `chainId` configuration option wasn't wired up correctly before.
Fixes #554 
=> fix: useEnsName chainId

.changeset/hot-moles-happen.md, packages/react/src/utils/parseContractResult.test.ts, packages/react/src/utils/parseContractResult.ts
It turns out that if a contract method returned a tuple of structs, this would cause `parseContractResult` to run into an issue where it would assign `null` to the returned array. In some cases, this also [produced an error](https://github.com/tmm/wagmi/pull/552#issuecomment-1149537541).
I have fixed those cases in this PR, and have also tightened up the test cases for `parseContractResult` abit to also cover complex return types.
=> fix: fixed `parseContractResult` for more complex contract types

.changeset/poor-carpets-repeat.md, packages/core/package.json, packages/core/src/actions/accounts/signTypedData.ts, packages/react/package.json, packages/react/src/hooks/accounts/useConnect.ts, packages/react/src/hooks/accounts/useDisconnect.ts, packages/react/src/hooks/accounts/useNetwork.ts, packages/react/src/hooks/accounts/useSignMessage.ts, packages/react/src/hooks/accounts/useSignTypedData.ts
- Add `types` field to package.json
- Adds const assertion for mutation keys
- Remove separate `TypedDataDomain` and `TypedDataField` types and add into `SignTypedDataArgs`
Fixes #591
=> feat: add package.json types field

.changeset/five-toes-begin.md, .changeset/rare-lemons-clean.md, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
Usage of the `reloadOnDisconnect: false` option in older versions of the Coinbase Wallet extension, and seemingly the current version of the mobile app from what I can see, causes the following error when trying to connect:
This has been fixed in `@coinbase/wallet-sdk@3.3.0` where they now check for the presence of the `disableReloadOnDisconnect` function before executing it.
I wouldn't normally submit a patch to update a dependency like this, but in this case I think it makes sense since the Coinbase Wallet connector is effectively broken with the current dependency ranges. This will help ensure consumers get a working version when they update to the latest wagmi.
=> fix: update Coinbase Wallet SDK to fix connection errors

docs/pages/docs/comparison.en-US.mdx
There are tests in [useDapp](https://github.com/TrueFiEng/useDApp/tree/master/packages/core/src/hooks).
We also have integration tests which use [playwright](https://playwright.dev/).
There is no web3react since version 1.*.
Our hooks have typechain support.
=> Update useDapp status

.changeset/lemon-bulldogs-live.md, .changeset/silly-dots-flow.md, .prettierignore, docs/pages/docs/getting-started.en-US.mdx, docs/pages/index.en-US.mdx, packages/core/src/actions/accounts/signTypedData.test.ts, packages/core/src/actions/accounts/signTypedData.ts, packages/core/src/utils/normalizeChainId.test.ts, packages/core/src/utils/normalizeChainId.ts, packages/react/src/hooks/accounts/useSignTypedData.test.ts, packages/react/src/hooks/contracts/useContractWrite.test.ts, packages/react/src/hooks/transactions/useSendTransaction.test.ts, packages/react/test/utils.ts
Use `domain.chainId` to validate and switch chain before signing in `useSignTypedData`. Similar to https://github.com/tmm/wagmi/pull/611
=> feat: use domain.chainId to validate and switch chain before signing typed data

.changeset/thick-doors-bow.md, packages/react/src/hooks/accounts/useAccount.test.ts, packages/react/src/hooks/accounts/useConnect.test.ts, packages/react/src/hooks/accounts/useDisconnect.test.ts, packages/react/src/hooks/accounts/useNetwork.test.ts, packages/react/src/hooks/utils/useSyncExternalStoreWithTracked.test.tsx, packages/react/src/hooks/utils/useSyncExternalStoreWithTracked.ts, packages/react/test/index.tsx, packages/react/test/utils.ts
=> fix: `useSyncExternalStoreWithTracked` equalityFn should return truthy when there are no tracked keys

docs/pages/docs/WagmiConfig.en-US.mdx
[Migration guide](https://wagmi.sh/docs/migration-guide#05x-breaking-changes) states that `client` is now required. Docs are stale on previous versions stating is it optional
Your ENS/address: `harry.eth`
=> remove client(optional) as it is required since 0.5.x

packages/core/src/constants/chains.ts
Small fix to update the `id` definition for the chain `foundry` as it was using `chainId.hardhat` instead of `chainId.foundry`.
Possibly worth mentioning that the values are the same for `hardhat` and `foundry` in the [`chainId` constant](https://github.com/tmm/wagmi/blob/e4bd79fe8da24e80100515c516a358ccdd71509a/packages/core/src/constants/chains.ts#L18-L19), not sure if these IDs are actually supposed to be the same. 🤷‍♀️
```
hardhat: 31_337,
foundry: 31_337,
```
Your ENS/address: `lochie.eth`
=> Use correct chainId in Foundry chain definition

.changeset/mighty-mice-sip.md, .changeset/slow-pumpkins-love.md, .config/hardhat.config.ts, examples/_dev/src/components/Account.tsx, examples/_dev/src/components/ReadContract.tsx, examples/_dev/src/components/ReadContracts.tsx, examples/_dev/src/pages/_app.tsx, package.json, packages/core/src/actions/contracts/multicall.test.ts, packages/core/src/actions/contracts/multicall.ts, packages/core/src/actions/contracts/readContracts.test.ts, packages/core/src/actions/contracts/readContracts.ts, packages/core/src/errors.ts, packages/core/src/index.test.ts, packages/core/src/index.ts, packages/react/src/hooks/contracts/useContractRead.ts, packages/react/src/hooks/contracts/useContractReads.ts, packages/react/src/index.test.ts, packages/react/src/index.ts, pnpm-lock.yaml
Fixes #645
When a contract method returned zero data (`0x`) for any call in a multicall, this would cause the function to throw an error, resulting in the multicall returning nullish data unexpectedly. This PR guards for the case where a call could return zero data, and warns the user that the function does not exist on the targeted contract.
=> fix: fix multicall returning nullish data for all calls unexpectedly

docs/pages/docs/client.en-US.mdx
Missing comma in autoConnect example
=> docs: missing comma in autoConnect

.changeset/big-candles-kneel.md, .changeset/smart-days-reflect.md
Fix broken release not containing `deepEqual` from `@wagmi/core` (#668 didn't include a release for `@wagmi/core`). Closes #669.
=> fix: broken release

.changeset/eighty-trains-doubt.md, packages/core/src/connectors/coinbaseWallet.ts
I was having import issues with Coinbase Wallet SDK while trying to use wagmi + RainbowKit in a Vite project. I noticed there's already an attempted workaround for this in wagmi but it didn't seem to work for me.
The original workaround checked whether `CoinbaseWalletSDK` was missing a `constructor` property, but this was evaluating as false because the imported object does have a constructor, i.e. `({}).constructor` exists, evaluating to `Object`.
Instead I'm opting to check whether the `CoinbaseWalletSDK` class is a function, and if it isn't, check whether it has a `default` property that _is_ a function.
By the way, I noticed that the workaround code path isn't used when running the Vite example in the wagmi repo and the regular default import seems to work fine. Were you aware of …
=> fix: update Vite import workaround for Coinbase Wallet SDK

.changeset/real-insects-hunt.md, packages/react/package.json, pnpm-lock.yaml
Lock `react-query` version since it was renamed to `@tanstack/query`
=> fix: lock query version

.changeset/gentle-squids-switch.md, packages/react/package.json, packages/react/src/hooks/providers/useProvider.test.ts, packages/react/src/hooks/providers/useProvider.ts, packages/react/src/hooks/providers/useWebSocketProvider.test.ts, packages/react/src/hooks/providers/useWebSocketProvider.ts, pnpm-lock.yaml
Fixes #732
- Fixes an issue where the `useProvider` hook would not update if `chainId` changes
- Refactor `useProvider` to use `useSyncExternalStoreWithSelector` to better support React 18
- Added test case to validate fixed behavior
=> fix: make chain aware providers great again

.changeset/quiet-impalas-doubt.md, .config/hardhat.config.ts, docs/pages/docs/hooks/useBalance.en-US.mdx, packages/core/src/actions/accounts/fetchBalance.test.ts, packages/core/src/actions/accounts/fetchBalance.ts, packages/react/src/hooks/accounts/useBalance.test.ts, packages/react/src/hooks/accounts/useBalance.ts
`useBalance` (via `fetchBalance`) was not formatting token balances correctly, where `token.decimals !== 18`. Raised in https://github.com/wagmi-dev/wagmi/discussions/737
=> fix: balance formatting for tokens

docs/pages/examples/sign-in-with-ethereum.en-US.mdx
I couldn't get SIWE working when following the example and it turned out it was because the `useCallback` dependency array was empty, so the callback wasn't being updated when `state.nonce` changed. This meant that the nonce in the SIWE message and the nonce in the session cookie didn't match.
Rather than updating the dependency array, I figured it's an over-optimisation for this example and could be left as a regular function definition, but I'm happy to update this if you disagree.
=> docs: fix stale callback in SIWE example

packages/core/src/errors.ts
added closing double quote for chain mismatch error
Your ENS/address: srujangurram.eth
=> Fixes error message missing closing double quote

.changeset/afraid-peas-tan.md, .changeset/calm-mugs-beam.md, .changeset/chilled-points-cry.md, .changeset/real-shoes-obey.md, .changeset/wicked-jeans-beam.md, docs/pages/docs/hooks/useContractWrite.en-US.mdx, docs/pages/docs/hooks/useSendTransaction.en-US.mdx, docs/pages/docs/migration-guide.en-US.mdx, examples/_dev/src/components/SendTransaction.tsx, examples/_dev/src/components/WriteContract.tsx, examples/_dev/src/components/WriteContractPrepared.tsx, packages/core/src/actions/contracts/writeContract.test.ts, packages/core/src/actions/contracts/writeContract.ts, packages/core/src/actions/transactions/sendTransaction.test.ts, packages/core/src/actions/transactions/sendTransaction.ts, packages/core/src/actions/transactions/waitForTransaction.test.ts, packages/react/src/hooks/contracts/useContractEvent.test.ts, packages/react/src/hooks/contracts/useContractWrite.test.ts, packages/react/src/hooks/contracts/useContractWrite.ts, packages/react/src/hooks/transactions/useSendTransaction.test.ts, packages/react/src/hooks/transactions/useSendTransaction.ts, packages/react/src/hooks/transactions/useWaitForTransaction.test.ts
For Prepare Hooks, the term "dangerous" sounds scary, but the dangerous usage isn't really "dangerous" at all. The term "reckless" fits better.
don't be so reckless.
https://www.youtube.com/watch?v=JIrUqsB-0vw
=> feat: prefer "reckless" > "dangerous"

.changeset/pink-guests-speak.md, packages/core/src/constants/chains.ts
Fix canonical native asset symbols to ETH for
Ropsten, Rinkeby, Goerli, Kovan, Optimism Kovan, Arbitrum Rinkeby, Optimism Goerli
Your ENS/address: vijay.eth
=> Fix canonical native asset symbols to ETH

.changeset/perfect-dragons-sell.md, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
Adds custom name mapping for the [1inch Wallet](https://1inch.io/wallet/) app's injected provider.
=> feat: add custom name mapping for 1inch Wallet injected provider

.changeset/red-spiders-add.md, packages/react/package.json
Fix `MockConnector` entrypoint path
=> fix: mock connector entrypoint path

.changeset/nervous-trains-glow.md, packages/core/src/chains.ts, packages/core/src/constants/blockExplorers.ts, packages/core/src/constants/chains.ts, packages/core/src/constants/rpcs.ts, packages/react/src/chains.test.ts, packages/react/src/chains.ts
Adds the chain configuration for the Sepolia Testnet
The Ethereum Foundation will deprecate the Ropsten, Rinkeby, and Kiln testnets soon and encourages people to switch to Goerli or Sepolia instead.
> Users and developers are encouraged to migrate ASAP to Goerli or Sepolia to test Ethereum in a post-merge context.
Source: https://blog.ethereum.org/2022/06/21/testnet-deprecation/
- [Official Client Configuration Repository](https://github.com/eth-clients/sepolia)
- [Sepolia.dev Website](https://sepolia.dev/)
- [Announcement that encourages use of Sepolia](https://blog.ethereum.org/2022/06/21/testnet-deprecation/)
- [Sepolia Etherscan](https://sepolia.etherscan.io/)
Your ENS/address: 0x00A59Ec1F4BF9718EeE07078141b540272BAB807 (skeith.eth)
=> Add support for the Sepolia testnet

docs/pages/examples/send-transaction.en-US.mdx
Apparent typos in wagmi.sh/examples, specifically `Send Transaction.` I could be wrong because I'm new, please check. 
- [x ] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
0x9E7393D824A83DE0Ca971e90b196E92209CfE4D2
=> Fix potential typo in wagmi/examples/Send Transaction/Step 3

.changeset/blue-terms-crash.md, packages/core/src/connectors/coinbaseWallet.ts
This PR fixes an issue (#966) in `CoinbaseWalletConnector` where the browser extension would unintendedly reset the network when the browser is refreshed.
=> fix: respect connected coinbase wallet extension chain id

.github/workflows/main.yml, package.json, packages/core/src/actions/accounts/fetchBalance.test.ts, packages/core/src/actions/contracts/prepareWriteContract.test.ts, packages/core/src/actions/contracts/writeContract.test.ts, packages/core/test/constants.ts, packages/core/test/index.ts, packages/core/test/utils.ts, packages/react/src/hooks/accounts/useBalance.test.ts, packages/react/src/hooks/contracts/useContractEvent.test.ts, packages/react/src/hooks/contracts/useContractWrite.test.ts, packages/react/src/hooks/contracts/useDeprecatedContractWrite.test.ts, packages/react/src/hooks/contracts/usePrepareContractWrite.test.ts, packages/react/test/index.tsx
This PR updates the `wagmiContractConfig` to use the new wagmi mint example contract. Since the new contract supports a `tokenId` argument to the `mint` function, we can remove the `getTotalSupply` test util.
=> tests: update test wagmi contract

docs/pages/docs/providers/configuring-chains.en-US.mdx
=> docs: fix typo in configuring-chains.en-US.mdx

.changeset/rich-stingrays-fold.md, packages/core/src/utils/configureChains.ts
Fixes #1030. Celo does not provide `gasLimit` or `difficulty` on `eth_getBlockByNumber`, this causes ethers to blow when validating the block causing `useFeeData`/`fetchFeeData` to throw an error.
We can definitely make this implementation scalable to other chains which could behave the same way, but might need a bit of thought around an API. This is just a quick fix for now.
=> fix: make ethers block format validator compatible with Celo

.changeset/eight-avocados-agree.md, packages/core/src/constants/blockExplorers.ts, packages/core/src/constants/chains.ts
Adds new Arbitrum Goerli instance of Arbiscan to the chain's block explorers and marks it as the default option
=> feat: add arbitrum goerli arbiscan block explorer

.changeset/proud-snakes-pretend.md, packages/core/src/connectors/metaMask.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
Add support for https://www.core.app/
Core Wallet is detected as metamask: when it's installed, both`isMetaMask` and `isAvalanche` are set to true (I believe it's similar to brave wallet).
=> feat(injected): add avalanche core wallet

.changeset/mighty-masks-rest.md, packages/core/src/actions/contracts/getContract.ts
Came across following typescript error when working with `getContract` function from `@wagmi/core` package (`ContractCtrl` is my file using this function).
```
Exported variable 'ContractCtrl' has or is using name 'EventListener' from external module "/node_modules/@wagmi/core/dist/declarations/src/actions/contracts/getContract" but cannot be named.
```
Not entirely sure what the root cause of this error is, but exporting `EventListener` interface resolves it. My hunch is that it's something to do with ts semantics and using associated functionality of this type "outside" of its definition.
=> Export EventListener type

.changeset/fresh-mice-boil.md, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
Moves `abitype` from `devDependencies` to `dependencies`.
Fixes https://github.com/wagmi-dev/wagmi/issues/1077
=> fix: abitype to deps

.changeset/slimy-hounds-work.md, package.json, packages/core/package.json, packages/core/src/index.ts, packages/react/package.json
Some module types not exported from `@wagmi/core` were not able to be resolved when consumed by `wagmi`. For example, `import("@wagmi/core/src/types/contracts").GetReturnType` isn't resolvable from `useContractRead`'s declaration file (below).
```ts
export declare function useContractRead<TAbi extends Abi | readonly unknown[], TFunctionName extends string>({ abi, address, functionName, args, chainId: chainId_, overrides, cacheOnBlock, cacheTime, enabled: enabled_, isDataEqual, select, staleTime, suspense, watch, onError, onSettled, onSuccess, }?: UseContractReadConfig<TAbi, TFunctionName>): import("../utils/query/useQuery").UseQueryResult<import("@wagmi/core/src/types/contracts").GetReturnType<{
abi: TAbi;
functionName: TFunctionName;
}>, Error>;
```
This fixes the resolution by exporting …
=> fix: expose module types

.changeset/wild-mails-study.md, packages/react/src/hooks/accounts/useAccount.ts
Fixes https://github.com/wagmi-dev/wagmi/issues/777
`useAccount` `onConnect`/`onDisconnect` callbacks weren't firing when the client auto-connected before the event listener was set up in `React.useEffect`. Removing the side effect and using render instead fixes this.
=> fix: onConnect/onDisconnect callbacks

packages/core/src/connectors/metaMask.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
Add support for https://www.ripio.com/portal/
Ripio Portal is detected as MetaMask: when it's installed (only on some dApps), both isMetaMask and isPortal are set to true. In most cases isPortal will be true and isMetaMask false.
=> feat: add Ripio Portal injected wallet

packages/core/src/constants/blockExplorers.ts, packages/core/src/constants/chains.ts
add etherscan config for optimism goerli -> [Block Explorers | Optimism Docs](https://community.optimism.io/docs/useful-tools/explorers/#)
Your ENS/address: yujiym.eth
=> fix: add optimism goerli etherscan

.changeset/chilly-laws-tickle.md, packages/react/src/index.test.ts, packages/react/src/index.ts
This PR fixes #1164 and ensures that we are exporting the `Client` from the React entrypoint.
=> fix: export `Client` from React entrypoint

docs/pages/docs/client.en-US.mdx
On the client docs, the createStorage function wasn't imported from wagmi so would have failed. Adding the import for clarity and to stop confusion.
Your ENS/address: riklomas.eth
=> Missing import in client docs

.changeset/cold-berries-breathe.md, packages/core/src/client.test.ts, packages/core/src/client.ts
This PR fixes an issue where the active chains (`client.chains`) would be populated with the last known active chains when the user is disconnected.
=> fix: active chains populating when disconnected

.changeset/healthy-eels-attend.md, packages/core/src/actions/ens/fetchEnsName.ts
This PR fixes #1187 and ensures that addresses are checksummed for `lookupAddress`.
=> fix: checksum address for fetchEnsName

.changeset/chatty-horses-admire.md, .changeset/spotty-timers-prove.md, docs/components/web3/Account.tsx, docs/pages/docs/hooks/useBalance.en-US.mdx, docs/pages/docs/hooks/useEnsAvatar.en-US.mdx, docs/pages/docs/migration-guide.en-US.mdx, docs/pages/examples/connect-wallet.en-US.mdx, examples/_dev/src/components/Account.tsx, examples/_dev/src/components/Balance.tsx, packages/core/src/actions/accounts/fetchBalance.test.ts, packages/core/src/actions/accounts/fetchBalance.ts, packages/core/src/actions/ens/fetchEnsAvatar.test.ts, packages/core/src/actions/ens/fetchEnsAvatar.ts, packages/react/src/hooks/accounts/useBalance.test.ts, packages/react/src/hooks/accounts/useBalance.ts, packages/react/src/hooks/ens/useEnsAvatar.test.ts, packages/react/src/hooks/ens/useEnsAvatar.ts
Changing `addressOrName` to `address`. Related #1135 
=> refactor: addressOrName to address

docs/pages/docs/hooks/useSignTypedData.en-US.mdx
typo signTypeDataAsync -> signTypedDataAsync
=> fix: signTypedDataAsync typo

.changeset/sweet-planes-cheer.md, packages/core/src/connectors/metaMask.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
Add Support for [https://kuwallet.com](https://kuwallet.com)
KuCoinWallet Wallet is detected as metamask: when it's installed, both `isMetaMask` and `isKuCoinWallet` are set to true
=> feat(injected): add kucoin wallet support

.changeset/heavy-pots-wonder.md, packages/core/src/actions/accounts/signTypedData.test.ts, packages/core/src/actions/accounts/signTypedData.ts, packages/core/src/actions/contracts/prepareWriteContract.test.ts, packages/core/src/actions/contracts/prepareWriteContract.ts, packages/core/src/actions/contracts/writeContract.test.ts, packages/core/src/actions/contracts/writeContract.ts, packages/core/src/actions/transactions/prepareSendTransaction.test.ts, packages/core/src/actions/transactions/prepareSendTransaction.ts, packages/core/src/actions/transactions/sendTransaction.test.ts, packages/core/src/actions/transactions/sendTransaction.ts, packages/core/src/connectors/coinbaseWallet.ts, packages/core/src/connectors/injected.ts, packages/core/src/errors.ts, packages/core/src/utils/assertActiveChain.test.ts, packages/core/src/utils/assertActiveChain.ts, packages/react/src/hooks/accounts/useSigner.ts, packages/react/src/hooks/contracts/usePrepareContractWrite.test.ts, packages/react/src/hooks/contracts/usePrepareContractWrite.ts, packages/react/src/hooks/transactions/usePrepareSendTransaction.test.ts, packages/react/src/hooks/transactions/usePrepareSendTransaction.ts
#940 improved `chainId` validation, but did not address an edge case where `Signer` could still be on the wrong chain because it was not configured at the `Connector`-level (resulting in [low-level ethers error](https://github.com/wagmi-dev/wagmi/issues/1222)).
Fixes #1222 
=> feat: validate chain configured for connector

.changeset/tender-cats-suffer.md, docs/pages/docs/hooks/useContractInfiniteReads.en-US.mdx, docs/pages/docs/hooks/useContractRead.en-US.mdx, docs/pages/docs/hooks/useContractReads.en-US.mdx, packages/react/src/hooks/contracts/useContractInfiniteReads.ts, packages/react/src/hooks/contracts/useContractRead.ts, packages/react/src/hooks/contracts/useContractReads.ts
Missed adding a default for `structuralSharing` in #1260. We need to default `structuralSharing` to our own implementation because [React Query's data comparison function does not support the ethers `Result` type as it is not JSON serializable.](https://github.com/wagmi-dev/wagmi/issues/648#issuecomment-1173396960)
=> feat: add default for structuralSharing

docs/pages/docs/hooks/useProvider.en-US.mdx, docs/pages/docs/hooks/useWebSocketProvider.en-US.mdx
`useProvider` page had a code example for `useWebSocketProvider`, while `useWebSocketProvider` had the reverse.
Your ENS/address: `lochie.eth`
=> fix: useWebSocketProvider and useProvider docs mixup

.changeset/ten-beans-enjoy.md, packages/react/src/hooks/accounts/useAccount.ts
Fixes `useAccount`'s `onConnect` `isReconnected` flag so it consistently returns the correct result.
=> fix: useAccount onConnect isReconnected flag

.changeset/poor-crabs-walk.md, .changeset/rich-lobsters-stroll.md, packages/core/src/actions/contracts/prepareWriteContract.ts, packages/react/src/hooks/contracts/useContractWrite.test.ts, packages/react/src/hooks/contracts/usePrepareContractWrite.ts
Sets `abi` return type value for `usePrepareContractWrite`/`prepareContractWrite` to generic value `TAbi` (when not inferrable as `Abi`) instead of `readonly unknown[]` so that type info is preserved.
=> fix: return type for prepareContractWrite

.changeset/fast-ears-destroy.md, packages/react/src/hooks/accounts/useBalance.ts, packages/react/src/hooks/contracts/useContractRead.ts, packages/react/src/hooks/network-status/useFeeData.ts, packages/react/src/hooks/utils/useInvalidateOnBlock.ts
Fixed an issue where `useContractRead` would perform an unnecessary rerender if another hook had `watch` enabled.
=> fix: unnecessary `useContractRead` rerender

.changeset/smart-ways-cross.md, packages/core/src/connectors/metaMask.ts
Fix issue reconnecting after disconnect with `MetaMaskConnector` in MetaMask mobile browser. Closes #1365 
=> fix(MetaMaskConnector): MetaMask mobile browser connect after disconnect

.changeset/witty-moose-double.md, packages/react/src/hooks/contracts/useContractInfiniteReads.test-d.ts, packages/react/src/hooks/contracts/useContractInfiniteReads.ts, packages/react/src/hooks/contracts/useContractRead.test-d.ts, packages/react/src/hooks/contracts/useContractRead.ts, packages/react/src/hooks/contracts/useContractReads.test-d.ts, packages/react/src/hooks/contracts/useContractReads.ts, packages/react/src/types/index.ts
Fixes #1375
Fixed an issue where transforming `useContractRead`, `useContractReads` or `useContractInfiniteReads`'s return data via `select` wasn't inferring the type.
=> fix: infer `select` return type

.changeset/five-bottles-dress.md, packages/core/src/connectors/walletConnect.ts
Fixes #1374
This PR fixes a case where a WalletConnect wallet may not resolve the `wallet_switchEthereumChain` method. Specifically, there seems to be a bug in Trust Wallet where this method doesn't resolve upon switching chains, which means that `switchChain` never resolves. 
Can reproduce in this [CodeSandbox](https://codesandbox.io/s/priceless-sunset-uslxmi?file=/pages/index.tsx) by switching chain. We should probably open an issue upstream to Trust Wallet to fix this (wherever their repo is?), but might be nice to implement this PR to set up the safe guard.
=> fix: switch chains via WalletConnect

.changeset/small-bikes-study.md, packages/core/src/actions/accounts/connect.ts
Check that `activeConnector` exists to ensure better error message.
=> feat: add check for active connector

.changeset/perfect-coats-drop.md, packages/react/src/hooks/utils/useSyncExternalStoreWithTracked.test.ts, packages/react/src/hooks/utils/useSyncExternalStoreWithTracked.ts
After reading https://github.com/wagmi-dev/wagmi/discussions/1401#discussioncomment-4280127, I realised that we should actually be defaulting to an equality check when there are no values being tracked. 
This PR fixes the behavior in `useSyncExternalStoreWithTracked` to ensure that the hook rerenders when no values are being tracked. We don't want to skip the equality check when there no tracked keys. This also [reaches parity with React Query's behavior](https://github.com/TanStack/query/blob/24ac9f9e00f28a317c7bd2be2f28de0131b40b25/packages/query-core/src/queryObserver.ts#L620).
=> fix: ensure that hook rerenders when no values are being tracked

.changeset/cuddly-eggs-shout.md, packages/react/src/hooks/contracts/useContractRead.ts, packages/react/src/hooks/contracts/useContractReads.ts, packages/react/src/hooks/network-status/useFeeData.ts, packages/react/src/hooks/utils/useInvalidateOnBlock.ts
`useInvalidateOnBlock` would sometimes still fetch when `enabled: false`
=> fix: useInvalidateOnBlock respect enabled

.changeset/rude-rabbits-push.md, packages/core/src/errors.test.ts, packages/core/src/errors.ts, tsconfig.json
Even though we are targeting ES2021, this refactors `Error.internal` to `Error.cause` (h/t https://github.com/wagmi-dev/wagmi/discussions/871)
=> refactor: add error options with cause

.changeset/honest-dolphins-pay.md, packages/core/src/actions/accounts/signTypedData.test.ts, packages/core/src/actions/accounts/signTypedData.ts
This PR omits the `EIP712Domain` type from `signTypedData` before sending it over to ethers.
=> fix: omit `EIP712Domain` type from `signTypedData`

.changeset/pink-fans-bathe.md, packages/core/src/client.test.ts, packages/core/src/client.ts
This PR fixes an issue where the wagmi client wouldn't rehydrate the store in local storage when `autoConnect` is truthy.
=> fix: ensure that store is rehydrated when `autoConnect` is truthy

.changeset/dull-numbers-travel.md, packages/core/src/connectors/metaMask.ts, packages/core/src/types/index.ts, packages/core/src/utils/getInjectedName.test.ts, packages/core/src/utils/getInjectedName.ts
Add Support for https://phantom.app/
Phantom Wallet is detected as metamask: when it's installed, both isMetaMask and isPhantom are set to true
=> feat: add phantom wallet support

.changeset/ten-vans-sin.md, docs/pages/core/connectors/_meta.en-US.json, docs/pages/core/connectors/mock.en-US.mdx, docs/pages/react/connectors/_meta.en-US.json, docs/pages/react/connectors/mock.en-US.mdx, packages/core/src/connectors/mock/connector.ts, packages/core/src/connectors/mock/provider.test.ts, packages/core/src/connectors/mock/provider.ts
- Adds documentation for `MockConnector`
- Updates `chainId` behavior to default to first chain from `chains` if not provided in `options` (closes #1343)
=> feat: MockConnector chainId

.changeset/stale-onions-smell.md, packages/core/src/actions/accounts/watchSigner.test.ts, packages/core/src/actions/accounts/watchSigner.ts
Fixes #1440 
Asserts that a `connector` exists before invoking the callback in `watchSigner`.
=> fix: assert `connector` exists in `watchSigner`

package.json, pnpm-lock.yaml
Remove pnpm `esbuild` override introduce in #1314 (fix in https://github.com/evanw/esbuild/commit/9ce5f94a49ff37635dfc221477640dfee11e036b)
=> chore: remove esbuild override

.changeset/weak-tips-eat.md, packages/core/src/actions/accounts/signMessage.ts, packages/core/src/actions/accounts/signTypedData.ts, packages/core/src/actions/transactions/sendTransaction.ts, packages/core/src/errors.ts
Converts custom ethers ["ACTION_REJECTED"](https://github.com/ethers-io/ethers.js/commit/d9897e0fdb5f9ca34822929c95a478634cc2a460) error to standard RPC Error.
Closes #1499 
=> fix: unwrap ethers action rejected errors

.changeset/ninety-wolves-fly.md, packages/react/src/hooks/network-status/useBlockNumber.ts
Fixes #1467
Fixed an issue where `useBlockNumber` would return data when `watch` is enabled and `enabled` is falsy.
=> fix: `useBlockNumber` shouldn't watch when `enabled` is falsy.

docs/pages/core/migration-guide.en-US.mdx, docs/pages/react/migration-guide.en-US.mdx
The block explorer diff section of current latest migration guides (0.8.x core & 0.9.x React) is incorrect, compares to the [`@wagmi/chains` API](https://github.com/wagmi-dev/references/blob/46e53fb5bd8f45b8770a6596a0b88c1ca2671744/packages/chains/src/mainnet.ts#L21).
Your ENS/address: robertu.eth
=> fix(docs): incorrect block explorer of migration guide

.changeset/dry-seals-raise.md, .changeset/rude-phones-dress.md, packages/core/src/providers/alchemy.ts, packages/core/src/providers/infura.ts, packages/core/src/providers/jsonRpc.test.ts, packages/core/src/providers/public.test.ts, packages/core/src/providers/public.ts, packages/core/test/utils.ts, packages/react/.gitignore, packages/react/package.json
Using the full `Networkish` type in providers' instantiation allows custom `ensAddress` to be applied from chain definitions.
Sepolia does not have an official ENS registry deployed. Since I am working on some ENS frontend tooling and want to use a testnet, and I prefer to use sepolia for reasons, I deployed my own suite of ENS contracts. I then update the sepolia chain definition before creating the providers like so....
```js
import { mainnet, goerli, sepolia } from "@wagmi/chains";
export const supportedAppChains = [mainnet, goerli, sepolia] as const;
sepolia.contracts = {
...sepolia.contracts,
ensRegistry: {
address: "0xBc4693CB0F572b99f6aB4462602b5A0B8585010B",
},
};
```
We can then create our providers and init wagmi....
```js
const { providers, webSocketProviders } = …
```
=> feat: support custom ensAddress for providers

.changeset/silver-cars-complain.md, .github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, docs/pages/core/connectors/walletConnect.en-US.mdx, docs/pages/react/connectors/walletConnect.en-US.mdx, pnpm-lock.yaml
Updating `references/` submodule for WalletConnect v2 + docs.
=> feat: WalletConnect v2

docs/pages/core/actions/writeContract.en-US.mdx
Replaced a `core/…` path to a `react/`. The target page is located under the former even for core docs.
Your ENS/address: n/a
=> fix(docs): dead link

.changeset/yellow-toys-turn.md, packages/react/src/hooks/accounts/useSigner.test.ts, packages/react/src/hooks/accounts/useSigner.ts
Fixes #1622
This PR fixes an issue where switching accounts would not update the signer in `useSigner`.
Upon fixing this issue, I tested for regressions and noticed that our new implementation (introduced in `0.10.x`) of utilizing `.refetch()` doesn't work well with account changes & was also still causing issues where it would unnessessarily broadcast to other `useSigner`s in some cases. I refactored the implementation to one which is similar to how we had it before, and I am pretty confident this one is robust (no unnessessary rerendering & invalidates correctly on account/connector/chain id change).
=> fix: fixed issue where switching wallets would not update signer

docs/pages/core/actions/watchAccount.en-US.mdx, docs/pages/core/actions/watchBlockNumber.en-US.mdx, docs/pages/core/actions/watchMulticall.en-US.mdx, docs/pages/core/actions/watchNetwork.en-US.mdx, docs/pages/core/actions/watchPendingTransactions.en-US.mdx, docs/pages/core/actions/watchProvider.en-US.mdx, docs/pages/core/actions/watchReadContract.en-US.mdx, docs/pages/core/actions/watchReadContracts.en-US.mdx, docs/pages/core/actions/watchSigner.en-US.mdx, docs/pages/core/actions/watchWebSocketProvider.en-US.mdx
The docs on the pages with watch methods doesn`t contain information on how to unsubscribe from subscriptions.
Added "Return Value" section to every watch<...> page except watchContractEvent.
=> Add watch functions return value (unwatch) info

.changeset/quick-carrots-rhyme.md, packages/core/src/types/index.ts
- Added `isRainbow` to `InjectedProviderFlags` type
- Opened sister PR on `wagmi-dev/references` to implement `isRainbow` provider flag: https://github.com/wagmi-dev/references/pull/51
- [✔️] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
Your ENS/address: danielsinclair.eth
=> Added support for Rainbow injected provider

.changeset/quiet-emus-march.md, package.json, packages/cli/package.json, packages/cli/src/commands/generate.ts, pnpm-lock.yaml
Fix generated address object key type so it's alway a number. (Won't be a number in JS `Object.keys` still, which is fine. Just need it to be for type inference.)
=> fix(cli): generated chain key type

.changeset/red-beds-change.md, packages/cli/src/plugins/etherscan.ts
Add celoscan to the etherscan plugin
Your ENS/address: 0x59A6AbC89C158ef88d5872CaB4aC3B08474883D9
=> Add celoscan to etherscan plugin

docs/theme.config.tsx
This PR fixes the "Edit this page on GitHub" permalinks. Currently these links double up on the `pages` path and lead to broken links (e.g `https://github.com/wagmi-dev/wagmi/tree/main/docs/pages/pages/core/getting-started.en-US.mdx`)
`lochie.eth`
=> fix: broken "Edit this page on GitHub" 

docs/pages/react/migration-guide.en-US.mdx
`chainId` has been deprecated in favor of `id`, per `Chain` (https://github.com/wagmi-dev/references/blob/main/packages/chains/src/types.ts#L10)
- [ x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
Your ENS/address: jonsadka.eth
=> Update migration-guide.en-US.mdx to reflect correct id

.changeset/mighty-pans-cheer.md, packages/core/package.json, packages/react/package.json
Locked ethers peer dependency version to >=5.5.1 <6
Fixes https://github.com/wagmi-dev/wagmi/issues/1785
=> chore: lock ethers peer dep

docs/components/docs/Header.tsx, docs/theme.config.tsx
1. I have updated the copyright year at the Homepage Footer from the hard-coded _2022_ to _2023_ using `Date()` module, this will prevent yearly updates on the same issue. The year can also be changed in _LICENSE_ and _references/LICENSE_ but that is best to be decided by the wagmi team and not by me.
2. I have also added `alt` attributes to the images on the landing page for better SEO.
Your ENS/address: _Not Available_
**P.S.: I am new to open-source contribution, so I am all ears to feedback.**
=> updated copyright year to 2023 (using Date module), also added img alt

.changeset/fair-icons-explain.md, packages/cli/src/plugins/etherscan.ts
replace arbitrum rinkeby chain id, etherscan api endpoint pair for arbitrum goerli
https://docs.arbiscan.io/v/goerli-arbiscan
https://docs.alchemy.com/changelog/q3-2022-deprecation-of-arbitrum-rinkeby-in-favor-of-arbitrum-goerli
Your ENS/address: shotaro.eth
=> Arbitrum Rinkeby Deprecated, Replace with Arbitrum Goerli

docs/pages/react/typescript.en-US.mdx
Fixed the spelling mistake on the typescript page in the `Callout` section. 
changes made : 
```diff
- fetchi
+ fetch
```
shivbhonde.eth
=> Fix spelling mistake `fetchi` on typescript page

docs/pages/core/connectors/injected.en-US.mdx
Fixes broken link to the `getInjectedName.ts` file.
Similar to #1559
=> Update injected.en-US.mdx: fix broken link

.changeset/afraid-kiwis-marry.md, packages/cli/src/utils/packages.ts
https://github.com/wagmi-dev/wagmi/issues/1877
yarn detection for wagmi cli was broken.  This is because the userAgent for yarn berry includes npm in the string.
Fix: Check yarn before checking npm
- [ x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
=> Fix yarn berry package detection

.changeset/eight-vans-taste.md, packages/cli/src/utils/packages.ts
In a previous pr we fixed one bug about yarn 3.0 but there is another one.  `yarn list` does not exist in yarn berry
Fix: use yarn why instead
I yarn linked my wagmi and tried on the repro 
- I also changed the package name hardhat to 'asdfasdf' to test that validation still fails
- I also verified yarn why exists in yarn classic
=> fix: Fix automatic package detection with yarn^3

.changeset/tasty-dolphins-flash.md, packages/cli/src/plugins/__snapshots__/react.test.ts.snap, packages/cli/src/plugins/react.ts
fix generated read hooks `select` type
```ts
// before
const { data } = useMyGeneratedHook({
select: data => data[0].toBigInt()
}) 
data
// ^? type data = [BigNumber] | undefined
// after fix
const { data } = useMyGeneratedHook({
select: data => data[0].toBigInt()
}) 
data
// ^? type data = bigint | undefined
```
=> cli: fix generated read hooks select type

docs/pages/core/actions/watchMulticall.en-US.mdx
Changes the documentation for `watchMulticall` to reference return type as `unwatch` instead of `data`
nascob.eth
=> Fix documentation for watchMulticall()

.changeset/strange-cooks-rush.md, packages/cli/src/plugins/react.ts
During creation of `address` types in `react` plugin, it seems that it was hard coded to `0x{String}` and this will cause an issue if people using the package have overridden `AddressType` as mentioned here in wagmi [docs](https://wagmi.sh/docs/typescript#configuring-internal-types). 
Instead of hard coding `0x{String}` we can leverage `Address` type exported from `wagmi` . 
To test checkout `Steps to reproduce` of #1915, after generating hooks change the type of `address?: 0x{String}` -> `address ?: Address` in one of the write hooks. 
This solution seemed minimal, but happy to reconsider/revamp the whole solution 🙌 
Thanks 🙌
Fixes #1915 
shivbhonde.eth
=> Fix wagmi/cli react plugin incompatible Address type for usePrepare and useFunctionWrite

docs/pages/core/connectors/walletConnectLegacy.en-US.mdx, docs/pages/react/connectors/walletConnectLegacy.en-US.mdx
I believe `version` option was carried over accidentally from previous documentation
Your ENS/address: asimetriq.eth
=> docs: Remove version option from WalletConnectLegacyConnector

.changeset/sweet-items-sneeze.md, docs/pages/core/connectors/injected.en-US.mdx, docs/pages/core/connectors/metaMask.en-US.mdx, docs/pages/react/connectors/injected.en-US.mdx, docs/pages/react/connectors/metaMask.en-US.mdx
Removes shimChainChangedDisconnect shim (no longer necessary)
References PR https://github.com/wagmi-dev/references/pull/177
Closes #1941 
=> refactor: remove `shimChainChangedDisconnect`

docs/pages/cli/getting-started.en-US.mdx
"npm run" doesn't work by default with npm.  I had to add a wagmi script to package.json to get it working.
npx instead, just works and is always installed along npm.
Your ENS/address: 0xc5a23c04f05D8F1bc27344E394654B21bE9CC488
=> Change "npm run" for "npx" in plugin docs

packages/core/src/actions/contracts/watchContractEvent.ts
Fixed inaccurate comment on the `eventName` property of type `WatchContractEventConfig`.
N/A
=> update WatchContractEventConfig doc

.changeset/tough-onions-work.md, packages/core/src/actions/accounts/signTypedData.test.ts, packages/core/src/actions/accounts/signTypedData.ts, packages/core/src/actions/contracts/prepareWriteContract.test.ts, packages/core/src/actions/contracts/prepareWriteContract.ts, packages/core/src/actions/contracts/writeContract.test.ts, packages/core/src/actions/contracts/writeContract.ts, packages/core/src/actions/transactions/prepareSendTransaction.test.ts, packages/core/src/actions/transactions/prepareSendTransaction.ts, packages/core/src/actions/transactions/sendTransaction.ts, packages/core/src/utils/assertActiveChain.test.ts, packages/core/src/utils/assertActiveChain.ts, packages/react/src/hooks/contracts/usePrepareContractWrite.test.ts, packages/react/src/hooks/transactions/usePrepareSendTransaction.test.ts, pnpm-lock.yaml
We forgot to remove an ethers workaround (that we could not opt-out of) we did for active chain assertion: https://github.com/wagmi-dev/wagmi/pull/1232.
Should have no negative side-effects as we do the assertion in the block above in `assertActiveChain.ts`.
=> fix: remove ethers assert chain workaround

docs/pages/core/migration-guide.en-US.mdx, docs/pages/react/WagmiConfig.en-US.mdx
Mainnet used but not defined/import
After import:-
=> Mainnet not import #2312

docs/pages/cli/create-wagmi.en-US.mdx
There was a small typo in the `create-wagmi` documentation where extra hyphens appeared before the template flag.
Your ENS/address: salief.eth
=> gets rid of extra hyphens in npm example

.changeset/slow-socks-pump.md, packages/core/src/actions/viem/watchWalletClient.ts
Fixes an issue where synchronous switch chain behavior (WalletConnect v2) would encounter chain id race conditions in `watchWalletClient`.
=> fix: assert `chainId` on `watchWalletClient`

.changeset/short-lions-deliver.md, .changeset/wise-penguins-yawn.md, packages/core/src/actions/contracts/prepareWriteContract.test.ts, packages/core/src/actions/contracts/prepareWriteContract.ts, packages/core/src/actions/contracts/writeContract.test.ts, packages/core/src/actions/contracts/writeContract.ts, packages/core/src/types/utils.ts, packages/core/src/utils/getParameters.ts, packages/react/src/hooks/contracts/useContractWrite.test.ts, packages/react/src/hooks/contracts/useContractWrite.ts, packages/react/src/hooks/contracts/usePrepareContractWrite.test.ts, packages/react/src/hooks/contracts/usePrepareContractWrite.ts
Added the ability to pass `account` override to contract write Actions & Hooks.
Ref: #2432
=> feat: add `account` to contract write actions/hooks

docs/pages/index.zh-CN.mdx
click the Getting Started button in the original CN website will redirect to 404, and I found it's because the prefix of link is fault
the original link is: https://wagmi.sh/zh-CN/core/getting-started
the edited link is: https://wagmi.sh/zh-CN/react/getting-started
Your ENS/address: 0xE3aa98316cc1c1611381c29725b69c6Ece3B6658
=> Fix the website redirect error

packages/react/src/hooks/utils/useInvalidateOnBlock.ts
Fixes the `onBlock` callback in the  `useInvalidateOnBlock` hook being declared on every render, resulting in frequent re-creation of the listener in `useBlockNumber` and far more fetch requests than expected under certain circumstances.
=> fix useInvalidateOnBlock onBlock fn is declared on every render

.changeset/fresh-cups-trade.md, packages/react/src/hooks/contracts/useContractRead.ts
Add `keepPreviousData` query prop to `useContractRead` similar to `useContractReads`.
It's a patch while waiting for v2, where [all query keys/functions are expected to be exported](https://github.com/wagmi-dev/wagmi/discussions/2207).
Related: https://github.com/wagmi-dev/wagmi/pull/2042/files#r1142721538
=> feat: add keepPreviousData query prop to useContractRead

README.md, docs/components/docs/Sponsors.tsx, docs/pages/examples/connect-wallet.en-US.mdx
- Add Rainbow as a sponsor in the README
- Add Rainbow to the Docs sponsors list
- Add RainbowKit to the README
- Add RainbowKit to the Examples > Connect Wallet section
- Requires first merging the sister PR with wordmark assets: https://github.com/wagmi-dev/.github/pull/3
=> chore: add rainbow sponsor

docs/pages/cli/getting-started.en-US.mdx
Looking at these docs today it was bothering me that every section title was a verb except the first one
Your ENS/address: weicurry.eth
=> Fix nit in doc

.changeset/popular-baboons-remember.md, packages/cli/src/commands/generate.ts, packages/cli/src/config.ts, packages/cli/src/plugins/blockExplorer.ts, packages/cli/src/plugins/sourcify.ts, packages/core/src/actions/accounts/fetchBalance.ts, packages/core/src/actions/contracts/fetchToken.ts, packages/core/src/actions/contracts/readContracts.test.ts, packages/core/src/actions/contracts/watchMulticall.test-d.ts, packages/core/src/actions/contracts/watchReadContract.test-d.ts, packages/core/src/actions/contracts/watchReadContracts.test-d.ts, packages/core/src/actions/ens/fetchEnsAddress.ts, packages/core/src/actions/ens/fetchEnsName.ts, packages/core/src/actions/transactions/sendTransaction.ts, packages/core/src/index.ts, packages/react/src/index.ts
Changes `Address` type import from ABIType to viem so it always references the ABIType version coming from viem.
References PR
- https://github.com/wagmi-dev/references/pull/338
=> refactor: switch address type import

docs/pages/examples/send-transaction.en-US.mdx
The `request` parameter is removed in the upgrade. reference: https://wagmi.sh/react/migration-guide#usesendtransaction
I was trying to go through the example, and I found out that the code in the example didn't match the package of the current version. What I do is remove the `request` parameter as the top-level parameter in `usePrepareSendTransaction` when creating `config`, which is used as the parameter in `useSendTransaction`.
Here is the reference: https://wagmi.sh/react/migration-guide#usesendtransaction
- [ v ] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
Your ENS/address: 0xakira.eth
=> Update send-transaction.en-US.mdx: remove `request` in `usePrepareSendTransaction`

docs/pages/core/ethers-adapters.en-US.mdx
The Ethers Adapter page for core wagmi contained incorrect naming for the `getEthersProvider` and `getEthersSigner` functions. They were erroneously referred to as `useEthersProvider` and `useEthersSigner`, names that pertain to the react section. This PR addresses this issue by correcting the names in the documentation.
https://wagmi.sh/core/ethers-adapters
vitormarthendal.eth
=> Docs fix function names on ethers adapter core

docs/pages/react/typescript.en-US.mdx
The docs for ABIType are now at https://abitype.dev/, so it is best to send people there rather than to the github.
Your ENS/address:  qbzzt.eth
=> Update the abitype link to the main doc site

docs/pages/examples/custom-connector.en-US.mdx
Addressed a broken link in the [Create Custom Connector example](https://wagmi.sh/examples/custom-connector)
Your ENS/address: **notniuq.eth**
=> bugfix: addresses broken walletconnect link

docs/pages/react/connectors/walletConnect.en-US.mdx
I've been reading `walletConnect.en-US.mdx` and I found link for [`chainId` config on useConnect](/core/hooks/useConnect#chainid-optional) is broken because of core documentation doesn't have hook documents.
I think linking to [/react/hooks/useConnect#chainid-optional](/react/hooks/useConnect#chainid-optional) can be quick fix for broken link.
and plus this page has same problem above.
https://github.com/wagmi-dev/wagmi/blob/bff2aa41637e7facb4356f4cbda5d537c0c88fa5/docs/pages/core/connectors/walletConnect.en-US.mdx#L47
Your ENS/address: `applemartini.eth`
=> fix broken internal link in walletConnect.en-US.mdx

packages/react/src/hooks/accounts/useAccount.ts
fixes #1998
fix is mostly re-doing https://github.com/wagmi-dev/wagmi/commit/3cef111b1e30120233d8754b33587cdf94aedd8f in a more simple way. Have confirmed that:
* The problem fixed in #1679 is still fixed
* The problem in #1998 is fixed (tested example repo working after change)
=> fix: `useAccount` should not unsubscribe from zustand when re-render

.changeset/wet-cups-remember.md, packages/react/src/hooks/accounts/useAccount.ts, packages/react/src/hooks/accounts/useNetwork.ts
The use-case is to make DApps interactive using providers + one connector, while lazy-importing many connectors; this PR resolves #2665 which was a blocker.
Although this PR adds reactivity w.r.t. the `useConfig()` return value, it does not actually use said return value, since:
* the `@wagmi/core` API does not accept `config`
* I didn't want to re-implement the `@wagmi/core` methods
Further discussion here: #2666
=> feat(react): `useAccount` and `useNetwork` will react to changing `config` prop of `WagmiConfig`

docs/pages/core/actions/writeContract.en-US.mdx
As referenced in Issue #2684 and the [@wagmi/core migration guide](https://wagmi.sh/core/migration-guide#writecontract), `wait` is no longer included in the writeContract return value. The [current docs](https://wagmi.sh/core/actions/writeContract#return-value) still reference this field, so this PR removes the erroneous reference.
Your ENS/address: saintmaxi.eth
=> Docs: remove wait from @wagmi/core writeContract return value

docs/components/web3/Account.tsx, docs/pages/react/hooks/useEnsAvatar.en-US.mdx
closes https://github.com/wagmi-dev/wagmi/issues/2765
useEnsAvatar hook does not accept the `address` parameter.
=> Docs: fix useEnsAvatar example code

docs/pages/examples/sign-message.en-US.mdx
Just fixing the name used in the useEffect hook.
=> Fix var name typo in Sign Message example

docs/pages/cli/configuration/options.en-US.mdx
Fix link for `Array config` in [`Config options#out`](https://wagmi.sh/cli/configuration/options#out) page of documentation.
0x2244Ba7fC96b1dFCaaaC57521139c7487402b94e
=> Update options.en-US.mdx to fix `Array config` link

docs/pages/react/providers/public.en-US.mdx
I may have misunderstood something, but as a result of analyzing the source code, it seems that the property related to provider weight below is no longer available.
If the options below are still valid and I think I misanalyzed them, please close the pull request.
=> docs: delete provider weight

docs/pages/examples/sign-in-with-ethereum.en-US.mdx
As per SIWE docs:
- siweMessage.validate is now deprecated in favour of siweMessage.verify. 
- Consequentially, the siweMessage.verify arguments are changed to accept an object (see spec attached)
- Return value of siweMessage.verify has also changed to add a success statement. 
- Consequentially, the nonce is now contained inside the data object.
Verify param spec:
export interface VerifyParams {
/** Signature of the message signed by the wallet */
signature: string;
/** RFC 4501 dns authority that is requesting the signing. */
domain?: string;
/** Randomized token used to prevent replay attacks, at least 8 alphanumeric characters. */
nonce?: string;
/**ISO 8601 datetime string of the current time. */
time?: string;
}
- Changed siweMessage.validate(signature) (deprecated) to …
=> Updates SIWE to latest version

docs/pages/examples/sign-in-with-ethereum.en-US.mdx
As per SIWE docs:
- siweMessage.validate is now deprecated in favour of siweMessage.verify. 
- Consequentially, the siweMessage.verify arguments are changed to accept an object (see spec attached)
- Return value of siweMessage.verify has also changed to add a success statement. 
- Consequentially, the nonce is now contained inside the data object.
Verify param spec:
export interface VerifyParams {
/** Signature of the message signed by the wallet */
signature: string;
/** RFC 4501 dns authority that is requesting the signing. */
domain?: string;
/** Randomized token used to prevent replay attacks, at least 8 alphanumeric characters. */
nonce?: string;
/**ISO 8601 datetime string of the current time. */
time?: string;
}
=> Follow up of previous PR to update SIWE w change to /api/me

.changeset/gorgeous-peaches-trade.md, packages/cli/src/plugins/react.ts
This PR modifies how the chain ID is sourced in `useContractRead`s generated from `wagmi/cli/react`.
**problem**: if there's no connected wallet, `useContractRead` hooks generated from `wagmi/cli/react` won't run. (more context inline: https://github.com/wagmi-dev/wagmi/pull/2946#discussion_r1306682870)
**This PR**
Now, hooks will fall back to public provider's chain ID (using wagmi's `useChainId` hook) if both the following are true:
- `useNetwork()` returns an empty object (=> no connected wallet).
- `config.chainId` is false (=> the dev didn't pass `chainId` in their call).
**The result:** hooks generated from `wagmi/cli/react` now run when the user's wallet isn't connected.
Your ENS/address: aeolian.eth
=> feat(cli): fallback to default public provider's chain id

docs/pages/core/actions/watchBlockNumber.en-US.mdx
As per the issue raised, I confirmed that the listen argument in watchBlockNumber is not optional. We have to mention that to listen to the new block's numbers. Hence, I removed the optional text against the listen argument in [wagmi/docs/pages/core/actions/watchBlockNumber.en-US.mdx](https://github.com/wagmi-dev/wagmi/blob/5e4bc8e26aa9bfc28f654c2d01a38c8d1d7ecc4e/docs/pages/core/actions/watchBlockNumber.en-US.mdx#L52)
Your ENS/address:  0xf2E841bb430B45BC6AC3EA5e24EEee039877E3FA
=> removed optional from listen in watchBlockNumber

docs/pages/react/providers/alchemy.en-US.mdx
The current version shows an error from TypeScript. Looking at the docs, the stallTimeout should be further down.
Here is an error that exists from the current examples:
Argument of type '{ apiKey: string; stallTimeout: number; }' is not assignable to parameter of type 'AlchemyProviderConfig'.
Object literal may only specify known properties, and 'stallTimeout' does not exist in type 'AlchemyProviderConfig'.ts(2345)
(property) stallTimeout: number
The same issue is present for all Provider docs -> subsection: "stallTimeout (optional)"
If this change needs to be made to all, ping me and I'll update them.
0xd3BCe6934f7433946a416A0344E64A835d957d73
=> Move stallTimeout in alchemy.en-US.mdx

.changeset/hip-olives-cheer.md, packages/core/src/actions/contracts/writeContract.ts, packages/core/src/actions/transactions/sendTransaction.ts
It is suspected that some wallets may be missing the `chainChanged` event causing wagmi active chain to become out of sync. 
Passing the `chainId` to the viem action will ensure we perform an additional chain id check against `eth_chainId` (instead of just `chainChanged` event).
=> fix: pass `chain` to `sendTransaction`/`writeContract`

.changeset/popular-ligers-camp.md, packages/core/src/actions/ens/fetchEnsAddress.ts, packages/core/src/actions/ens/fetchEnsAvatar.ts, packages/core/src/actions/ens/fetchEnsResolver.ts
Seems that synchronously importing `normalize` causes runtime side-effects to leak into initial page load: https://github.com/adraffy/ens-normalize.js/blob/main/src/lib.js#L172
h/t to @saihaj for identifying the perf bottleneck: https://github.com/saihaj/wagmi-performance-profiling
=> feat: change `normalize` to a dynamic import

docs/pages/react/hooks/useSignTypedData.en-US.mdx
Update documentation to reflect version 1.x.x breaking changes on useSignTypedData
=> Rename signTypedData 'value' to 'message'

docs/pages/core/providers/configuring-chains.en-US.mdx, docs/pages/react/providers/configuring-chains.en-US.mdx
There is an incorrect description in part of the sample code for retryDelay.
The description "retryCount" should be changed to "retryDelay".
Reason for setting VALUE at 150
There were only two places in the code where the retryDelay value was mentioned.
I referred to those.
＊value (150) is based on the description in the MOCK test code.↓
https://github.com/wagmi-dev/wagmi/blob/1fb735b3ada01eff6944073ff8406d5b0d74fc04/packages/connectors/src/mock/connector.test.ts#L174
https://github.com/wagmi-dev/wagmi/blob/1fb735b3ada01eff6944073ff8406d5b0d74fc04/packages/connectors/src/mock/provider.test.ts#L159
=> Fix incorrect "retryDelay" example.

docs/pages/react/hooks/useContractWrite.en-US.mdx
Fix documentation here https://wagmi.sh/react/hooks/useContractWrite#value-optional
Just a mistaken import. Should be `parseEther` not `parseGwei`, since `parseEther` is used
Should be: `import { useContractWrite, parseEther } from 'wagmi'`
Currently:
0xc4cA8f910702555F0AD3f81edF17DC82b0F98Bce
=> Developer documentation: Use correct import

docs/react/getting-started.md
currently points to this
https://beta.wagmi.sh/react/WagmiProvider
I updated it to this
https://beta.wagmi.sh/react/api/WagmiProvider
esm.eth
=> fix: doc link missing /api path

.changeset/sharp-windows-add.md, docs/pages/core/chains.en-US.mdx, docs/pages/react/chains.en-US.mdx, packages/core/src/chains.test.ts, packages/react/src/chains.test.ts
Removes the Celo Cannoli testnet, which is [deprecated](https://forum.celo.org/t/cannoli-testnet-deprecation-announcement/6796).
Your ENS/address: `0xarthur.xyz`
=> Removes Celo Cannoli testnet

docs/pages/examples/connect-wallet.en-US.mdx
Improving docs. I was reading and integrating and notice a minor mistake in docs.
https://wagmi.sh/examples/connect-wallet#step-3-display-connected-account
=> docs: correct example for fetching ens avatar

.changeset/hot-mails-scream.md, packages/connectors/src/injected.ts
The latest release of Phantom includes an empty `ethereum.providers` array. This causes the InejectedConnector to return an `undefined` provider. This PR fixes that so that the latest Phantom release (and potentially other wallets) can be used once again.
Your ENS/address: kalis.eth
=> Fix a bug where injected wallets with an empty providers array could not connect

.changeset/hip-buttons-march.md, packages/react/src/hooks/useWaitForTransactionReceipt.test.ts, packages/react/src/hooks/useWaitForTransactionReceipt.ts
* fixed condition causing `useWaitForTransactionReceipt` to be enabled when `hash` is `undefined`
* added tests
Your ENS/address: aquatik.eth
=> fix: useWaitForTransactionReceipt enabled state

packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/metaMask.ts, packages/core/src/connectors/injected.ts
* fixes a bug where `switchChain` fails when user does not already have the chain configured with their wallet
* use `rpcUrls.default` when requesting `wallet_addEthereumChain`
Your ENS/address: aquatik.eth
=> fix: use rpcUrls.default when requesting wallet_addEthereumChain

docs/pages/core/chains.en-US.mdx
`confluxESpace` is already added to the view chains but not listed in the document. This PR adds the `confluxESpace` to the chain list as well as `confluxESpaceTestnet`. 
=> Add Conflux eSpace to chain list

docs/pages/core/chains.en-US.mdx, docs/pages/react/chains.en-US.mdx
This PR contains the adding of ```neonMainnet``` chain. For whatever reason in the [docs page](https://wagmi.sh/core/chains) ```neonMainnet``` was missing, but ```neonDevnet``` was added. This is the **[proof](https://github.com/wevm/viem/blob/main/src/chains/index.test.ts#L101)** of viem supporting both of them.
=> add neonMainnet

packages/connectors/src/walletConnect.ts
> [!NOTE]
> To be merged on December 7th
This PR removes required namespaces in WalletConnect session proposals
=> refactor: updated walletconnect connector

.changeset/happy-terms-stare.md, docs/.vitepress/sidebar.ts, docs/core/api/actions/getTransactionCount.md, docs/react/api/hooks/useTransactionCount.md, packages/core/src/actions/getTransactionCount.test.ts, packages/core/src/actions/getTransactionCount.ts, packages/core/src/exports/actions.test.ts, packages/core/src/exports/actions.ts, packages/core/src/exports/index.test.ts, packages/core/src/exports/index.ts, packages/core/src/exports/query.test.ts, packages/core/src/exports/query.ts, packages/core/src/query/getTransactionCount.test.ts, packages/core/src/query/getTransactionCount.ts, packages/react/src/exports/index.test.ts, packages/react/src/exports/index.ts, packages/react/src/exports/query.test.ts, packages/react/src/hooks/useTransactionCount.test-d.ts, packages/react/src/hooks/useTransactionCount.test.ts, packages/react/src/hooks/useTransactionCount.ts
This PR Adds the core action `getTransactionCount` and the React hook `useTransactionCount ` for the Viem action [getTransactionCount ](https://viem.sh/docs/actions/public/getTransactionCount.html#gettransactioncount).
vitormarthendal.eth
=> Add `getTransactionCount` and `useTransactionCount`

docs/pages/examples/sign-message.en-US.mdx
The sample code in the 'Step 2: Add SignMessage Component' in the example of Sign Message https://wagmi.sh/examples/sign-message has a typo, the variable that is assigned as the return of `data` has been named as `signMessageData`
```
const { data: signMessageData, error, isLoading, signMessage, variables } = useSignMessage()
```
But in the return, it's still using `data` instead of `signMessageData`
```
{data && (
<div>
<div>Recovered Address: {recoveredAddress.current}</div>
<div>Signature: {data}</div>
</div>
)}
```
This commit is to replace `data` above with `signMessageData`
Fix the typo in the example code in https://wagmi.sh/examples/sign-message
- [ v ] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
Your …
=> Fix: typo in the sample code in sign-message.en-US.mdx

docs/pages/react/hooks/useWalletClient.en-US.mdx
Replaced the use of the `useContract` hook in favor of the action `getContract`, since this hook has been deprecated.
Your ENS/address: arthxr.eth
=> docs: replace useContract hook by getContract action

.changeset/pink-spoons-relate.md, packages/connectors/src/walletConnect.ts
Fixes the WalletConnect connector issue #3340 when calling `switchChain` for a chain that is not approved during initialization. We need to provide an actual block explorer URL instead of a block explorer object to an array of URLs.
=> fix: provide correct block explorer URL to WalletConnect

.changeset/plenty-mails-relate.md, packages/connectors/src/coinbaseWallet.ts
Fixes similar to #3341 issue but with Coinbase connector when calling switchChain. We need to provide an actual block explorer URL instead of a block explorer object to an array of URLs.
=> fix: provide correct block explorer URL to Coinbase connector

docs/pages/core/getting-started.en-US.mdx
Example shows `address` destructured from `connect`, but the variable in `connect's` return object is `account`
---
=> Docs: replace account with address in getting-started

.changeset/lazy-kiwis-run.md, packages/cli/src/plugins/react.test.ts, packages/cli/src/plugins/react.ts
Replace `functionName` for `eventName` when generating event watch hooks through the `useWatchContractEvent` function in the CLI's react plugin as the prop does not exist in that function.
=> Fix prop name when generating contract event watch hooks

docs/react/guides/ethers.md
fix typo "getEthersSigner" to "useEthersSigner"
In the example it shows import { getEthersSigner } hook from './ethers' however there is no exported getEthersSigner from the ethers example file. It should be useEthersSigner
=> Update ethers.md to fix typo "getEthersSigner" to "useEthersSigner"

.changeset/lazy-lemons-act.md, packages/cli/src/plugins/actions.ts
use `eventName` instead of `functionName` when generating contract events code.
Closes: https://github.com/wevm/wagmi/issues/3409
=> fix: use eventName instead of functionName

.changeset/three-spoons-drum.md, docs/core/api/actions/sendTransaction.md, packages/core/src/actions/sendTransaction.test.ts, packages/core/src/actions/sendTransaction.ts
Noticed that we didn't have the preluding gas estimate check in `sendTransaction`. Adding it means we reach parity with `writeContract` (w/ `simulateContract` being the prelude check), and consumers will be less surprised when unexpected errors happen upon tx execution.
=> fix: prelude gas estimation

docs/react/guides/migrate-from-v1-to-v2.md
`enabled` etc. are moved under `query`, thought it worths a mention in the migrate docs.
=> docs: Update migrate-from-v1-to-v2.md

.changeset/short-dolphins-serve.md, .changeset/tidy-dingos-confess.md, docs/.vitepress/sidebar.ts, docs/core/api/actions/getTransactionReceipt.md, docs/react/api/hooks/useTransactionReceipt.md, packages/core/src/actions/getTransactionReceipt.test.ts, packages/core/src/actions/getTransactionReceipt.ts, packages/core/src/exports/actions.test.ts, packages/core/src/exports/actions.ts, packages/core/src/exports/index.test.ts, packages/core/src/exports/index.ts, packages/core/src/exports/query.test.ts, packages/core/src/exports/query.ts, packages/core/src/query/getTransactionReceipt.test.ts, packages/core/src/query/getTransactionReceipt.ts, packages/react/src/exports/actions.test.ts, packages/react/src/exports/index.test.ts, packages/react/src/exports/index.ts, packages/react/src/exports/query.test.ts, packages/react/src/hooks/useTransactionReceipt.test-d.ts, packages/react/src/hooks/useTransactionReceipt.test.ts, packages/react/src/hooks/useTransactionReceipt.ts
- Added the `getTransactionReceipt` action.
- Added the `useTransactionReceipt` hook.
=> Feat: add `getTransactionReceipt` and `useTransactionReceipt`

docs/react/guides/migrate-from-v1-to-v2.md
A nitpicking as `writeContract` in the example won't accept an `undefined` type from what I can tell.
=> docs: update example in migrate-from-v1-to-v2.md

.changeset/silly-oranges-relax.md, .changeset/smart-grapes-join.md, packages/core/src/actions/getAccount.test-d.ts, packages/core/src/actions/getAccount.ts, packages/react/src/hooks/useAccount.test-d.ts, packages/react/src/hooks/useAccount.ts, packages/register-tests/react/src/useAccount.test-d.ts
Closes #3445
Previously, if you wanted to use the connected account's `chainId` (via `getAccount` and `useAccount`) with other actions/hooks `chainId` property, the type wasn't specific enough.
```ts
const config = createConfig({
chains: [mainnet, goerli],
transports: {
[mainnet.id]: http(),
[goerli.id]: http(),
},
})
const account = getAccount(config)
const ensName = await getEnsName({
address: '0x...',
chainId: account.chainId,
// Type 'number | undefined' is not assignable to type '1 | 5 | undefined'.
})
```
This is because `getAccount`/`useAccount` `chainId` doesn't need to adhere to the `config`, e.g. user switches wallet to an unsupported chain.
This PR updates types for `getAccount` and `useAccount` so that `chain` is either equal to a configured chain or `undefined`.
```ts
const …
```
=> feat: account chain typing

.changeset/loud-cats-sing.md, .changeset/smelly-mouse-help.md, packages/core/src/actions/getBlock.ts, packages/core/src/actions/getBlockNumber.ts, packages/core/src/actions/getBlockTransactionCount.ts, packages/core/src/actions/getEnsAddress.ts, packages/core/src/actions/getEnsAvatar.ts, packages/core/src/actions/getEnsName.ts, packages/core/src/actions/getEnsResolver.ts, packages/core/src/actions/getFeeHistory.ts, packages/core/src/actions/getTransaction.ts, packages/core/src/actions/readContract.ts
Remove `chainId` parameter from `readContract` calls in wagmi core action
Fixes https://github.com/wevm/wagmi/issues/3442
=> Fix: Remove chainId param from Viem readContract calls

docs/react/guides/migrate-from-v1-to-v2.md
fixes incorrect documentation of importing `normalize` from viem
=> fix: viem import path in migration docs

.changeset/giant-peas-perform.md, .changeset/gold-trains-peel.md, .changeset/moody-jars-wave.md, docs/.vitepress/sidebar.ts, docs/core/api/actions/getEnsText.md, docs/react/api/hooks/useEnsText.md, packages/core/src/actions/getEnsText.test.ts, packages/core/src/actions/getEnsText.ts, packages/core/src/exports/actions.test.ts, packages/core/src/exports/actions.ts, packages/core/src/exports/index.test.ts, packages/core/src/exports/index.ts, packages/core/src/exports/query.test.ts, packages/core/src/exports/query.ts, packages/core/src/query/getEnsText.test.ts, packages/core/src/query/getEnsText.ts, packages/react/src/exports/actions.test.ts, packages/react/src/exports/index.test.ts, packages/react/src/exports/index.ts, packages/react/src/exports/query.test.ts, packages/react/src/hooks/useEnsText.test.ts, packages/react/src/hooks/useEnsText.ts
- Added the `getEnsText` action.
- Added the `useEnsText` hook.
=> Feat: add `getEnsText` and `useEnsText`

.changeset/kind-adults-tan.md, packages/core/src/actions/reconnect.ts
Fixed an issue where connectors that share the same provider instance could reconnect when they have never been connected before.
=> fix: connector reconnect

.changeset/modern-crews-whisper.md, packages/core/src/createConfig.ts, playgrounds/next/src/app/layout.tsx, playgrounds/next/src/app/providers.tsx, playgrounds/next/src/wagmi.ts
Connectors have really long base 64 SVG `icon` strings. This ends up consuming cookie storage really fast.
In this PR, I have modified our persist strategy to only store "critical" connector properties that are needed before hydration (omitting `icon`).
=> fix: only persist critical properties

docs/shared/createConfig.md
Some of the links in the docs regarding the `Config` object's internal state were linking back to themselves/the first mention of state in that .md file, rather than linking down to the `State`(below):
Quick link to vercel deployment from below's github workflow:
[vercel.app/react/api/createConfig#state](https://wagmi-git-fork-seranged-docs-fix-in-createconfig-wevm.vercel.app/react/api/createConfig#state)
=> docs: fix createConfig links to 'State'

docs/react/api/hooks/useEnsAvatar.md
I propose those changes because the current documented version for `useEnsAvatar`'s `gatewayUrls` parameter doesn't work anymore.
For example:
```ts
const { data: avatar } = useEnsAvatar({
name: normalize(ensName!) || undefined,
chainId: mainnet.id,
gatewayUrls: {
ipfs: 'https://ipfs.io/',
},
});
```
had to be replaced with
```ts
const { data: avatar } = useEnsAvatar({
name: normalize(ensName!) || undefined,
chainId: mainnet.id,
gatewayUrls: ['https://ipfs.io/'],
});
```
and it now works on my side.
Additionally, it could be better documented what exactly should be passed as `gatewayUrls`, since there are no fields `ipfs` and `arweave` left, which explicitly set the gateways, and now the type has changed from `{ ipfs?: string | undefined; arweave?: string | undefined } | undefined` to …
=> docs: update `gatewaysUrl` in useEnsAvatar.md

.changeset/slimy-mayflies-mix.md, packages/cli/src/utils/getIsUsingTypeScript.test.ts, packages/cli/src/utils/getIsUsingTypeScript.ts
Improve wagmi/cli by detecting presence of wagmi.config.ts too, to decide TypeScript usage.
resolves #3505
=> feat: wagmi cli should consider wagmi.config.ts to decide if using ts

docs/react/api/chains.md
fixes: dead link to viem chains docs
=> fix: dead link in docs to viem

.changeset/seven-mugs-brake.md, .changeset/thirty-ducks-compete.md, packages/core/src/createConfig.test.ts, packages/core/src/createConfig.ts, playgrounds/vite-react/src/wagmi.ts
Adds code to automatically version and migrate Wagmi Config store between major and canary versions.
=> feat(core): migrate store

packages/core/src/actions/estimateFeesPerGas.test-d.ts, packages/react/src/hooks/useEstimateFeesPerGas.test-d.ts
Introduction of `maxFeePerBlobGas` in Viem seems to be causing these tests to fail in the [Wagmi regression tests on Viem](https://github.com/wevm/viem/actions/runs/7719107929/job/21041823398). 
Tweaking the test to match the return type, instead of strictly equal.
=> chore: tweak estimate fees type tests

docs/shared/connectors/injected.md
In the [connectors/injected#target](https://wagmi.sh/react/api/connectors/injected#target) section, you reference multiInjectedProviderDiscovery
Previous link: https://wagmi.sh/react/api/connectors/injected
Correct placement:  https://wagmi.sh/react/api/createConfig#multiinjectedproviderdiscovery
=> Update link to multiInjectedProviderDiscovery

packages/core/src/actions/getBlock.ts, packages/core/src/actions/getPublicClient.ts, packages/core/src/actions/getTransactionReceipt.ts, packages/core/src/actions/waitForTransactionReceipt.ts, pnpm-lock.yaml
[Narrowing formatter return types](https://github.com/wevm/viem/commit/b4cca34cc4a52e5f9697d958959b7f84bdc576b2) in Viem (to infer return type when no narrowed `chain` generic is passed) seems to [break internal types in Wagmi](https://github.com/wevm/viem/actions/runs/7791863392/job/21248850480). Previously, Viem returned `any` as the return type if it couldn't infer the chain, so that probably explains why it was not breaking before.
=> internal: widen internal types

.changeset/real-sheep-begin.md, packages/cli/src/plugins/etherscan.ts
Added the Optimism Sepolia chain id [11155420] to the `apiUrls` object in the etherscan plugin file. Also included is the corresponding API URL 'https://api-sepolia-optimistic.etherscan.io/api'.
=> Updated etherscan plugin to include Optimism Sepolia chainId

.changeset/slimy-toys-retire.md, packages/cli/src/plugins/etherscan.ts
Adding Holesky testnet api URL to the Etherscan plugin for wagmi CLI to use the commands for Holesky contracts.
=> Adding Holesky testnet to Etherscan plugin for wagmi CLI

.changeset/clever-poems-arrive.md, packages/cli/src/plugins/etherscan.ts
Added Arbitrum Sepolia testnet to Etherscan plugin in the wagmi cli to add support to generate for contracts published to arbitrum sepolia
=> Adding Arbitrum Sepolia testnet to Etherscan plugin for Wagmi CLI

.changeset/cuddly-dodos-visit.md, docs/cli/api/plugins/etherscan.md, packages/cli/src/plugins/etherscan.ts
SnowTrace is not maintained by EtherScan anymore but by AvaScan team. Etherscan has deployed their block explorer under https://snowscan.xyz now.
See VIEM PR for more info: https://github.com/wevm/viem/pull/1824
=> Replace SnowTrace with SnowScan an Etherscan product.

docs/react/api/hooks/useBalance.md
Add deprecated warning to the `unit` parameter in `useBalance`. Fix existing deprecated warning link for the `token` parameter.
=> docs: added deprecated warning to useBalance

.changeset/two-deers-love.md, packages/connectors/src/metaMask.ts, packages/core/src/connectors/injected.ts
This pull request resolves https://github.com/wevm/wagmi/issues/3652.
Following the steps outlined in the issue, I reproduced the error in the playground, applied this fix, and confirmed that it resolves the error.
=> Fix error when adding chains without explorers to MetaMask

docs/react/guides/tanstack-query.md
Added a `Devtools` section to tanstack query page in docs, to provide a workaround for "Cannot serialize BigInt" when tanstack devtools tries to display queryKeys in the devtool.
wagmi already does custom serialization on every hook level, but obviously client instance still has the default function to hash keys, and this is what is used by devtools.
=> Add a Devtools section to tanstack-query docs page

docs/core/api/actions/getPublicClient.md
1. `getPublicClient` isn't an async function, I don't see necessity to `await`
2. It's possible for `getPublicClient` to return an `undefined` value as far as I can see.
=> docs: update getPublicClient.md

.changeset/quick-hairs-nail.md, packages/core/src/actions/reconnect.test.ts, packages/core/src/actions/reconnect.ts
previously, calling `reconnect()` could potentially result in a race condition if `connect()` was called while reconnection was still pending. if `connect()` resolved before `reconnect()`, status would be set to `connected` and then be set to `disconnected` once `reconnect()` resolved (if there was no successful reconnection).
for me this issue was occurring via a combination of walletconnect's `getProvider()` taking a long time to resolve, and having automatic reconnection on mount enabled. if a user managed to connect before walletconnect's provider was initialised, they would connect and then be disconnected soon after.
there are definitely other potential solutions to this issue but i think this one is very straight forward with low impact on anything else.
Before submitting this …
=> fix: reconnect race condition

docs/core/guides/ethers.md, docs/react/guides/ethers.md
The async keyword makes the `getEtherSigner` return a promise when it shouldn't.
=> docs: remove unnecessary async keyword from getEthersSigner

.changeset/large-apricots-grow.md, packages/react/src/utils/query.ts
Previously, `Omit` broke the discriminated union that was returned in `UseMutationReturnType`.
By using `UnionOmit`, the union is preserved.
=> feat: improve `UseMutationReturnType`

docs/react/api/hooks/useWatchContractEvent.md
`useWatchContractEvent` docs incorrectly stated that return type is unsubscribe function, while in reality the return type is void
=> Update `useWatchContractEvent` return type description in docs

.changeset/violet-pianos-tickle.md, docs/cli/api/plugins/etherscan.md, packages/cli/src/plugins/etherscan.ts
Add Gnosis Chain support to Etherscan plugin.
=> Add Gnosis to Etherscan plugin

.changeset/hip-owls-battle.md, packages/core/src/actions/getConnectorClient.test.ts, packages/core/src/actions/getConnectorClient.ts
Fixes `getConnectorClient` `account` comparison
https://github.com/wevm/wagmi/pull/3605
=> fix: getConnectorClient account comparison

.changeset/olive-pears-wink.md, packages/cli/src/plugins/etherscan.ts
Sourced from https://docs.basescan.org/getting-started/endpoint-urls
This adds Base and Base Sepolia to the `@wagmi/cli/plugins` for Etherscan.
Didn't test -- just sourced the URLs and chain IDs from https://docs.basescan.org/getting-started/endpoint-urls 
- [😬] Added or updated tests (and snapshots) related to the changes made.
=> Add basescan to etherscan plugin

.changeset/two-sheep-shop.md, packages/core/src/connectors/injected.ts
Following https://github.com/wevm/wagmi/issues/3603
`shimDisconnect` should be considered before showing prompt for selecting account
=> injected.ts - check shimDisconnect before requestPermissions

.changeset/big-guests-live.md, packages/core/src/actions/writeContract.ts
`chainId` was not forwarded to the simulation call which was leading to calling wrong RPC node
=> Fix `writeContract` `chainId` forwarding during contract call simulation

.changeset/long-dogs-lie.md, packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/safe.ts, packages/core/src/connectors/injected.ts, packages/core/src/createConfig.ts, playgrounds/vite-react/src/App.tsx
- Refactors connector listeners so they aren't unnecessarily attached
- Updates injected connector behavior to listen for connections directly via wallets (e.g. MetaMask unlock or "Connect to this site")
=> refactor: connector listeners

.changeset/tame-bats-bow.md, packages/connectors/package.json, packages/connectors/src/metaMask.test.ts, packages/connectors/src/metaMask.ts, playgrounds/next/src/wagmi.ts, playgrounds/vite-core/src/wagmi.ts, playgrounds/vite-react/src/wagmi.ts, playgrounds/vite-ssr-react/lib/wagmi.ts, pnpm-lock.yaml
Updated MetaMask SDK to `0.18.5`.
=> feat: update metamask sdk

.changeset/tough-steaks-rush.md, packages/core/src/connectors/injected.ts
This is a workaround for the issue described in https://github.com/MetaMask/metamask-extension/issues/24247.
I've left a big inline comment explaining everything.
=> fix: metamask chain switch with missing net_version

.changeset/twelve-walls-deny.md, docs/dev/creating-connectors.md, packages/connectors/src/coinbaseWallet.ts, packages/core/src/actions/sendTransaction.test.ts, packages/core/src/actions/sendTransaction.ts, packages/core/src/actions/writeContract.ts, packages/core/src/connectors/createConnector.ts, packages/core/src/connectors/injected.ts
Adds a property to the connector to indicate whether it supports contract simulation. We can defer contract write simulation to the connector's wallet if it can accurately simulate the contract write & display contract revert reasons correctly. 
As a result, the time between user interaction and the wallet opening[^1] will become nearly instantaneous. 
This means it will resolve the issue of iOS Safari popup & universal link dismissal[^2] which some connectors rely on (ie. Coinbase Smart Wallet & the MetaMask SDK), provided that their wallets can accurately simulate contract write calls.
[^1]: TTOW: Time To Open Wallet.
[^2]: These dismissals occur if the intent does not get invoked within ~500ms of user interaction.
=> feat: connector property to skip contract simulation

.changeset/eighty-insects-love.md, packages/create-wagmi/src/cli.ts, packages/create-wagmi/templates/next/_npmrc, packages/create-wagmi/templates/vite-react/_npmrc, packages/create-wagmi/templates/vite-vanilla/_npmrc
Adds `.npmrc` with `legacy-peer-deps = true`. Seems that npm automatically installs optional peerdeps causing the initial install to take a while.
=> feat: add `.npmrc` to create-wagmi templates

.changeset/thick-gorillas-pretend.md, packages/cli/src/plugins/etherscan.ts
Add in Blastscan to official list of supported scanners so that people can easily pull contracts from the scanner.
=> feat: add blastscan url

.changeset/hot-rules-deny.md, .changeset/new-cobras-work.md, packages/connectors/src/safe.ts, packages/core/src/actions/reconnect.ts
Adds timeout `getInfo` called in `safe` connector since [non-Safe App iFrames cause it to not resolve](https://github.com/safe-global/safe-apps-sdk/issues/263#issuecomment-1029835840).
Fixes https://github.com/wevm/wagmi/issues/3961
=> feat(safe): add getInfo timeout

site/react/guides/chain-properties.md, site/vue/guides/chain-properties.md
It seems that there is an typo error on the returned value, result does not exist here, so i corrected the docs
Original version:
```import { useWaitForTransactionReceipt } from 'wagmi'
import { zkSync } from 'wagmi/chains'
const { data } = useWaitForTransactionReceipt({
hash: '0x16854fcdd0219cacf5aec5e4eb2154dac9e406578a1510a6fc48bd0b67e69ea9',
})
if (result.data?.chainId === zkSync.id) {
data?.logs
//    ^? (property) logs: ZkSyncLog[] | undefined
}
```
Corrected version:
```import { useWaitForTransactionReceipt } from 'wagmi'
import { zkSync } from 'wagmi/chains'
const { data } = useWaitForTransactionReceipt({
hash: '0x16854fcdd0219cacf5aec5e4eb2154dac9e406578a1510a6fc48bd0b67e69ea9',
})
if (data?.chainId === zkSync.id) {
data?.logs
//    ^? (property) logs: ZkSyncLog[] | undefined …
```
=> docs: fix chainId Data Property typo

.changeset/quick-onions-shout.md, packages/connectors/package.json, packages/connectors/src/coinbaseWallet.ts, pnpm-lock.yaml
Update Coinbase Wallet SDK to version 4.0.2
https://github.com/coinbase/coinbase-wallet-sdk/releases/tag/v4.0.2
=> Upgrade to coinbaseWallet v4.0.2

packages/connectors/src/coinbaseWallet.ts
`keysUrl` is an option to open a url other than keys.coinbase.com in the popup. It's not useful to devs at this time.
=> Don't expose keysUrl

.changeset/popular-files-worry.md, packages/connectors/package.json, packages/connectors/src/coinbaseWallet.ts, pnpm-lock.yaml
v4.0.3 fixes the `eth_chainId` response to match the spec. It was returning a number and now returns a hex, in line with https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_chainid
=> cbw sdk version bump

.changeset/fresh-pianos-prove.md, packages/core/src/actions/getConnectorClient.test.ts, packages/core/src/actions/getConnectorClient.ts, packages/core/src/actions/sendTransaction.ts, packages/core/src/errors/config.test.ts, packages/core/src/errors/config.ts, packages/core/src/exports/index.test.ts, packages/core/src/exports/index.ts, packages/vue/src/exports/index.test.ts, packages/vue/src/exports/index.ts, site/shared/errors.md
Adds a chain check to `getConnectorClient` since it's possible for connection state chain ID to get out of sync with the connector (e.g. [wallet bug](https://github.com/MetaMask/metamask-extension/issues/25097)).
=> feat: chain check

packages/cli/src/plugins/foundry.ts
Based on [forge-std](https://github.com/foundry-rs/forge-std/tree/master/src)'s source, the file is pascal-case `Test.sol` instead of `test.sol`. As a result, the test artifact gets picked up by wagmi cli and its types are unnecessarily (?) generated.
=> fix: `test.sol` should be `Test.sol`

packages/cli/src/plugins/foundry.ts
- Fixes #3951 
- Took this approach since the Mock files should probably be excluded anyway
- To prevent this from repeating in the future as `forge-std` drifts, might be a good idea to write a dedicated test to sanity check that the plugin works with `forge init`
- An alternative is to use the `Mock*.sol/**` glob pattern, but to prevent some edge-case wonkiness down the line where the user introduces a `MockingBird.sol` or something and it doesn't get picked up
=> fix: exclude forge-std Mock.sol files by default to prevent duplicate contract names

.changeset/shaggy-pillows-fold.md, packages/core/src/connectors/injected.ts, packages/core/src/createConfig.ts
Removes defensive [timeout](https://github.com/wevm/wagmi/blob/main/packages/core/src/connectors/injected.ts#L389-L391) for wallets delaying the reconnection process as it can cause unintended side effects https://github.com/wevm/wagmi/issues/4037. Moving forward, if a wallet hangs the reconnection process, it will be considered a wallet issue.
Closes #4037
=> feat(injected): reconnect timeout

site/vue/api/composables/useConnect.md
Fix a wrong import for the `useConnect` composable in Vue
=> Fix wrong import in docs code for useConnect in Vue

site/react/api/hooks/useTransactionCount.md
I believe the docs for `useTransactionCount` are not accurate, because the `eth_getTransactionCount` method returns only transactions that had been sent as per the spec: https://ethereum.github.io/execution-apis/api-documentation
=> update useTransactionCount documentation

.changeset/sweet-weeks-cry.md, packages/core/src/createConfig.test.ts, packages/core/src/createConfig.ts, packages/core/src/hydrate.test.ts, packages/core/src/hydrate.ts
Added revalidation for config chain ID in SSR and migration.
Fixes #3953
=> fix: chainId revalidate

.changeset/wise-starfishes-provide.md, packages/connectors/package.json, packages/connectors/src/metaMask.ts, pnpm-lock.yaml
Bumped MetaMask SDK and removed storage shim since SDK now uses `'wallet_revokePermissions'` to disconnect.
=> chore: bump mm sdk

site/core/api/actions/getChainId.md, site/react/api/hooks/useChainId.md, site/vue/api/composables/useChainId.md
Based on the discussion here https://github.com/wevm/wagmi/discussions/4030, I've updated docs for getChainId/useChainId to include explicit note that it should not be used as a method for getting the currently connected chain from connector, as it returns only the chains passed to the wagmi config.
=> docs: getChainId/useChainId clarification

.changeset/short-eyes-hide.md, .changeset/silent-countries-study.md, packages/react/src/hooks/useConnectorClient.test.tsx, packages/react/src/hooks/useConnectorClient.ts, packages/vue/src/composables/useConnectorClient.test.ts, packages/vue/src/composables/useConnectorClient.ts
This PR aims to prevent `useConnectorClient` running when account is **not** in `connected` state.
Took this along as a quick fix, feel free to close if this is a desired behaviour. Cheers.
=> FIX: useConnectorClient to be enabled only when connected or reconnecting

.changeset/real-squids-add.md, packages/connectors/src/metaMask.ts, packages/connectors/src/walletConnect.ts, packages/core/src/connectors/createConnector.ts, packages/core/src/createConfig.ts, packages/core/src/exports/index.test.ts, packages/core/src/exports/index.ts, packages/core/src/utils/extractRpcUrls.test.ts, packages/core/src/utils/extractRpcUrls.ts
Added functionality for consumer-defined RPC URLs (`config.transports`) to be propagated to the WalletConnect & MetaMask Connectors.
=> feat: propagate transport rpc urls to connectors

.changeset/neat-pants-care.md, packages/connectors/package.json, pnpm-lock.yaml
This PR updates `@walletconnnect/ethereum-provider` to version `2.15.0`
=> chore: update ethereum provider to 2.15.0

packages/connectors/src/metaMask.ts
This pr fixed the problem when using `import { metaMask } from 'wagmi/connectors'`.  If the user does not set the key `dappMetadata`, when building the package will report an error.
I find the latest readme in  the path `wagmi/site/shared/connectors/metaMask.md`   
It's shows that: 
```
dappMetadata
DappMetadata | undefined
Metadata about the dapp using the SDK.
Defaults to { name: 'wagmi' }.
```
But there is no synchronization in the code.  So I new the pull request to add this code into your repo. 
Without the code,  it will come out the error: 
`Error: You must provide dAppMetadata option (name and/or url)`
Which is checked by the metamask-sdk  [https://github.com/MetaMask/metamask-sdk/blob/a65d852432022906c1852168da7eadd4e26cf159/packages/sdk/src/sdk.test.ts#L151](url)
=> fix: metaMask dappMetadata add default value

.changeset/great-baboons-ring.md, packages/connectors/package.json, pnpm-lock.yaml
- Updates `@walletconnect/ethereum-provider` to version 2.15.1 fixing issue with `rollup` builds
=> Update @walletconnect/ethereum-provider to 2.15.1

.changeset/gentle-jobs-visit.md, .changeset/lazy-shrimps-occur.md, .changeset/long-pears-behave.md, packages/core/src/actions/getConnectorClient.test.ts, packages/core/src/actions/getConnectorClient.ts, packages/core/src/errors/config.test.ts, packages/core/src/errors/config.ts, packages/core/src/exports/index.test.ts, packages/core/src/exports/index.ts, packages/react/src/exports/index.test.ts, packages/react/src/exports/index.ts, packages/react/src/hooks/useConnectorClient.ts, packages/react/src/hooks/useWalletClient.ts, packages/vue/src/composables/useConnectorClient.ts, packages/vue/src/exports/index.test.ts, packages/vue/src/exports/index.ts, site/shared/errors.md
Adds guard to `getConnectorClient` and disables `useConnectorClient` when reconnecting and connector is not fully restored (doesn't have access to properties other than `id`, `name`, `type`, `uuid`.).
Closes #4238
=> fix: guard (get|use)ConnectorClient when reconnecting

.changeset/empty-falcons-approve.md, packages/connectors/package.json, pnpm-lock.yaml
- Updates `@walletconnect/ethereum-provider` to version `2.16.1`
=> chore: Update ethereum-provider to version 2.16.1

.changeset/hungry-colts-flow.md, packages/connectors/src/metaMask.ts, packages/core/src/connectors/injected.ts
It can hangs if "once" will catch an event with unexpected chainId.
UPD: But need to correctly unsubscribe handler( Maybe you can suggest better fix.
=> Fix race condition in injected.ts

.changeset/purple-hotels-smell.md, package.json, packages/connectors/package.json, packages/connectors/src/metaMask.ts, pnpm-lock.yaml, site/shared/connectors/metaMask.md
Related https://github.com/wevm/wagmi/pull/4323
=> feat: bump mm sdk

.changeset/brave-students-give.md, packages/core/src/connectors/injected.ts
“Uniswap Wallet” try to fake MetaMask wallet extension with the `isMetaMask` boolean.
But it is not yet in the "fake" MetaMask list here: https://github.com/EdouardBougon/wagmi/blob/a5e7927dfcb9b3930409056b50f810ed96ca4ffa/packages/core/src/connectors/injected.ts#L53-L81
Here the boolean used by Uniswap Wallet:
=> fix: uniswap wallet trying to make itself look like MetaMask

.changeset/curly-yaks-sin.md, packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/metaMask.ts, packages/core/src/connectors/createConnector.ts, packages/core/src/createConfig.test.ts, packages/core/src/createConfig.ts, packages/core/src/hydrate.ts, playgrounds/next/src/app/page.tsx, site/dev/creating-connectors.md
Allows connectors to specify `rdns` property and filters out matching EIP 6963 connectors from being created.
Related https://github.com/wevm/wagmi/pull/4328
=> feat(connectors): filter mipd by connector rdns

.changeset/tender-ads-compete.md, package.json, packages/connectors/package.json, packages/connectors/src/coinbaseWallet.ts, pnpm-lock.yaml
=> chore: clean up deps

.changeset/curvy-chefs-retire.md, packages/connectors/src/metaMask.ts
The option readonlyRPCMap should have a chainId in hexString as a key, not a number.
=> fix: MetaMask readonlyRPCMap type

.changeset/brown-bees-hope.md, packages/cli/package.json, packages/cli/src/commands/generate.ts, pnpm-lock.yaml
bumps chokidar to v4.0.1, removing 11 redundant dependencies. Since some dev deps depend on tar which depends on old chokidar, the lockfile didn't get smaller.
Since wagmi CLI doesn't expect globs in their watch mode - the change is backwards compatible. If they're required, I can reuse picomatch and wrap chokidar.watch args in a glob.
`pnpm test:cli` passes
=> chore(cli): bump chokidar

.changeset/olive-chefs-learn.md, packages/connectors/src/safe.ts
Fixes #4364 by using the same logic applied in the [MetaMask](https://github.com/wevm/wagmi/blob/main/packages/connectors/src/metaMask.ts#L240-L245) and [CoinbaseWallet](https://github.com/wevm/wagmi/blob/main/packages/connectors/src/coinbaseWallet.ts#L176-L181) connectors
=> fix: Safe connector not working in some Vite apps

.changeset/red-trains-switch.md, packages/core/src/actions/waitForTransactionReceipt.ts
This PR addresses a bug in the @wagmi/core library, specifically in the waitForTransactionReceipt function. The bug occurs when arguments are provided to skip simulation and gas estimation. The data field was not being passed to the eth_call function, which resulted in unexpected errors.
I've made a simple repository that has a script that reproduces this issue: https://github.com/AndriyAntonenko/wagmi-waitfortransaction-bug-poc
=> fix: waitForTransactionReceipt proper eth_call usage

site/cli/create-wagmi.md
- Explain how to select the template when you don't specify `--template` or `-t`, and what each option means.
- Remove the default template references, because there is no default template anymore.
=> docs(cli/create-wagmi): template selection

.changeset/unlucky-boats-dance.md, packages/core/src/connectors/injected.ts
Fixes the same issue encountered in #4227 and #4223 where the connector throws an error after switching to a chain that was just added via `'wallet_addEthereumChain'` but for the injected connector.
=> fix: injected connector throws error after switching to a chain that was just added via `'wallet_addEthereumChain'`.

.changeset/strange-bikes-lie.md, packages/connectors/package.json, pnpm-lock.yaml
Update @safe-global/safe-apps-provider so we can leverage EIP-5792 support. https://github.com/safe-global/safe-apps-sdk/pull/605
=> chore: update @safe-global/safe-apps-provider (EIP-5792 support)

.changeset/perfect-tigers-raise.md, packages/core/src/actions/codegen/createWatchContractEvent.ts
`createWatchContractEvent` actual behavior don't take `eventName` in considreation because it use `functionName` instead of `eventName`, probably a typo.
This PR fix that.
=> fix: eventName not properly set in createWatchContractEvent

site/react/api/hooks/useWaitForTransactionReceipt.md
There is 2 [Parameters](https://wagmi.sh/react/api/hooks/useWaitForTransactionReceipt#parameters-1) sections in `useWaitForTransactionReceipt` docs. The one using `core` should not be in `react` documentation.
This PR remove it.
=> fix: Remove duplicated Parameters from core doc in react useWaitForTransactionReceipt.md

.changeset/bright-suns-rush.md, packages/connectors/src/coinbaseWallet.ts, site/shared/connectors/coinbaseWallet.md
In latest `@coinbase/wallet-sdk`, we enriched one of the config param, `preference`, to be able to take `attribution` for onchain analytics, `keysUrl` for testing against different smart wallet env. So updating `@wagmi/connectors` to expose this new preference object to end users.
* this preference object can take arbitrary param, so it provides more flexibility to end user as we push out more new params
* this PR also replaced the deprecated class `CoinbaseWalletSDK` with the newly-introduced `createCoinbaseWalletSDK` to better align w js norm
https://github.com/user-attachments/assets/a8e0c81d-8f57-46de-b15a-8745b8c99d83
=> Use new init method + expose preference object

.changeset/late-hotels-report.md, packages/connectors/package.json, pnpm-lock.yaml
Bumps the metamask sdk version to 0.31.1 to fix the webpack dynamic import issue. Metamask SDK 0.31.0 has this issue and prevents @wagmi/connector from working in nextjs. See the next playground example on main to see the error. https://github.com/MetaMask/metamask-sdk/issues/1150
fixes #4432
=> fix: Bump Metamask SDK version to fix webpack dynamic import issue

.changeset/proud-knives-behave.md, packages/react/src/hooks/useEstimateGas.ts, packages/react/src/hooks/useSimulateContract.ts
Added the config parameter to `useConnectorClient` parameters when used in `useSimulateContract` and `useEstimateGas`. `useConnectorClient` would always call `useConfig` as config wasn't provided in the parameters, this broke providing a config to either hook and would mean `useConfig` was triggered in both hooks. This caused an error when `WagmiProvider` wasn't available in the context, as `useConnectorClient` would call `useContext(WagmiContext)` even if a config parameter was provided to the parent hooks.
=> Fix: pass config parameter to useConnectorClient in useSimulateContract and useEstimateGas

.changeset/plenty-ligers-smell.md, packages/cli/package.json, packages/cli/src/commands/generate.test.ts, packages/cli/src/commands/generate.ts, packages/cli/src/commands/init.test.ts, packages/cli/src/commands/init.ts, packages/cli/src/plugins/fetch.test.ts, packages/cli/src/plugins/fetch.ts, packages/cli/src/plugins/foundry.ts, packages/cli/src/plugins/hardhat.ts, packages/cli/src/utils/findConfig.ts, packages/cli/src/utils/getIsUsingTypeScript.ts, packages/cli/test/setup.ts, packages/cli/test/utils.ts, packages/create-wagmi/package.json, packages/create-wagmi/src/cli.test.ts, pnpm-lock.yaml
- Removed `fs-extra` for `node:fs`/`node:fs/promises`
- Removed `find-up` for [`escalade`](https://github.com/lukeed/escalade)
https://github.com/es-tooling/module-replacements/blob/main/docs/modules/README.md
=> refactor(cli): remove `fs-extra` and `find-up`

.changeset/spotty-kangaroos-approve.md, .changeset/thirty-camels-exercise.md, packages/connectors/src/walletConnect.test.ts, packages/connectors/src/walletConnect.ts, packages/core/src/actions/connect.test-d.ts, packages/core/src/actions/connect.ts, packages/core/src/actions/getConnectorClient.test.ts, packages/core/src/actions/getConnectors.ts, packages/core/src/actions/watchConnectors.ts, packages/core/src/connectors/createConnector.ts, packages/core/src/connectors/mock.test.ts, packages/core/src/connectors/mock.ts, packages/core/src/createConfig.test-d.ts, packages/core/src/createConfig.ts, packages/core/src/errors/config.test.ts, packages/core/src/errors/config.ts, packages/core/src/query/connect.ts, packages/react/src/hooks/useConnect.test-d.ts, packages/react/src/hooks/useConnect.ts, packages/react/src/hooks/useConnectors.ts, packages/register-tests/react/src/config.ts, packages/register-tests/react/src/useConnect.test-d.ts, packages/register-tests/vue/src/config.ts, packages/register-tests/vue/src/useConnect.test-d.ts, packages/vue/src/composables/useConnect.test-d.ts, packages/vue/src/composables/useConnect.ts, packages/vue/src/composables/useConnectors.ts, playgrounds/vite-react/src/App.tsx
Infer `config.connectors` so connector properties work with `useConnect()`/`connect`.
Related https://github.com/wevm/wagmi/discussions/4441
=> feat(core,react,vue): connect parameters

.changeset/warm-melons-joke.md, packages/connectors/package.json, packages/connectors/src/metaMask.ts, pnpm-lock.yaml
This PR aims to solve an issue where an app provides an empty string as the app URL.
Updated MetaMask SDK to version 0.31.2.
=> fix: update metamask sdk and fix metadata handling for empty URL

.changeset/nasty-planets-play.md, packages/connectors/src/metaMask.ts
Fix metadata handling for empty URLs.
In my previous commit, I used `||` to test for an empty string, but you replaced it with `??`, which no longer allows testing for `''`.
I have updated the test to use a ternary operator.
Let me know if you prefer a more explicit test, such as `name === ''`.
=> fix: metadata handling for empty URL

.changeset/big-radios-sip.md, package.json, packages/connectors/src/coinbaseWallet.test.ts, packages/connectors/src/coinbaseWallet.ts, packages/connectors/src/walletConnect.ts
This PR adds support for the instant onboarding mode of Coinbase Smart Wallet. It enables the same behaviour of the `Create Wallet` button on https://wallet.coinbase.com and skipping the first screen, where around 50% of my userbase clicked the wrong button. 
Use like this:
```typescript
(coinbaseWalletConnector as any).setInstantOnboarding(true);
await connectAsync({ connector: coinbaseWalletConnector });
```
https://github.com/user-attachments/assets/1d38ad7d-e78a-42c1-84ce-aad1117fba41
=> Coinbase Wallet: Add Support for Instant Onboarding mode

.changeset/nine-carrots-reply.md, packages/core/src/createConfig.ts, packages/core/src/createStorage.ts
Handles `setItem` errors in default storage
=> fix: default storage `setItem`

.changeset/afraid-cows-mix.md, packages/connectors/package.json, packages/connectors/src/metaMask.ts, playgrounds/vite-vue/src/wagmi.ts, pnpm-lock.yaml
Update MetaMask version and fix switch network
=> feat: update MetaMask version and fix switch network 

site/react/guides/read-from-contract.md, site/vue/guides/read-from-contract.md
The code will not run without a definition for this variable. I added a minimal config variable in-file so reader will know how to set one up for themselves.
=> Add wagmiContractConfig to example read-contract.tsx in read-from-contract.md

.changeset/breezy-parrots-exist.md, packages/core/src/createStorage.ts
Fixes #4479 
After debug with wagmi@2.14.5, I noticed that there's no params for `removeItem`, which will lead to the error 'illegal invocation', like in the screenshot.
``` js
export function getDefaultStorage() {
const storage = (() => {
if (typeof window !== "undefined" && window.localStorage)
return window.localStorage;
return noopStorage;
})();
return {
getItem: storage.getItem,
removeItem(key) {
try {
storage.removeItem(key);
} catch {}
},
setItem(key, value) {
try {
storage.setItem(key, value);
// silence errors by default (QuotaExceededError, SecurityError, etc.)
} catch {}
},
} satisfies BaseStorage;
}
```
I've already patched in my project, and it works well now.
=> fix params of removeItem

site/dev/contributing.md
This PR fixes a broken link in the `contributing.md` file. The link to the `Anvil` repository has been updated to point to the correct path in the Foundry repository. No additional changes are required as this resolves the issue.
=> fix: update broken link contributing.md

.changeset/nine-wombats-smash.md, packages/connectors/package.json, pnpm-lock.yaml
This PR bumps the Metamask SDK version (https://github.com/MetaMask/metamask-sdk/pull/1194)
=> chore: bumping metamask version

.changeset/eighty-socks-roll.md, packages/connectors/src/metaMask.ts
Rollback #4422. In this PR, `wallet_addEthereumChain` was called in the first place for all non-removable chains. This method has the side effect of requiring the user to update its MetaMask RPC when it's not matching the one specified in the request.
In this PR, we're moving back to the regular flow: try `wallet_switchChain`, and if it fails because the chain doesn't exist, try `wallet_addEthereumChain`. This flow is more consistent and aligned with the consequences of each method.
=> Fix chain switch: back to consistent switchChain before addChain

.changeset/eighty-coats-check.md, packages/connectors/package.json, pnpm-lock.yaml
This PR fixes an issue with the MetaMask connector where closing the connection modal wasn't properly triggering the expected error handling. Previously, when a user closed the MetaMask modal during connection, it should have resulted in a 4001 (user rejected request) error, but this wasn't happening correctly.
The fix is implemented by updating the MetaMask SDK from v0.31.5 to v0.32.0, which includes the proper error handling behavior.
=> fix: metamask connector error handling when closing modal

.changeset/short-icons-leave.md, packages/core/src/connectors/injected.ts
“Phantom” try to fake MetaMask wallet extension with the `isMetaMask` boolean.
But it is not yet in the "fake" MetaMask list here: https://github.com/wevm/wagmi/blob/651aa72827a79f38a89f5a64209592816c8e6492/packages/core/src/connectors/injected.ts#L571
=> fix: phantom wallet trying to make itself look like MetaMask

site/react/api/hooks/useEstimateGas.md
[wagmi docs](https://wagmi.sh/react/api/hooks/useEstimateGas#connector)
fix this page.
=> Fix the code to ensure line breaks

scripts/updateBlockExplorerPluginChains.ts
Noticed that `chainId` was defined as a `string`, while Sourcify API expects a `number`.
This could cause issues downstream.
Updated `chainId` to be a `number` to align with the expected format.
=> fix: fix chainId type in Sourcify API integration

site/core/guides/chain-properties.md, site/react/guides/chain-properties.md, site/vue/guides/chain-properties.md
Hi there! I fixed broken links in the documentation, specifically in the `chain-properties.md` files for the `core`, `react`, and `vue` sections. The old links to Viem's documentation (formatters and serializers) were pointing to non-existent pages, so I updated them to the correct ones:
=> docs: fixed broken links

site/vue/getting-started.md
This PR solves a small typo in the getting started guide for Vue.
=> Fix typo in getting-started.md

.changeset/young-houses-relate.md, packages/connectors/package.json, pnpm-lock.yaml
Updating `@safe-global/safe-apps-provider` version to `0.18.6` which includes [EIP-5792 Wallet Call API](https://github.com/ethereum/EIPs/pull/8826) recent changes.
Related:
https://github.com/safe-global/safe-apps-sdk/pull/637
=> fix: bump Safe Apps Provider version

.changeset/loose-mirrors-yawn.md, packages/cli/src/plugins/sourcify.ts
This PR upgrades the Sourcify plugin API endpoint from the deprecated V1 to the V2 endpoint.
FYI, it should also solve an issue where it was not possible to fetch partial-matched contracts. I hope this doesn’t break anything, but the V2 API does not seem to make the distinction anymore.
See here: <https://docs.sourcify.dev/docs/api/>
=> Use Sourcify v2 API in sourcify plugin

.changeset/silly-seals-laugh.md, packages/connectors/package.json, pnpm-lock.yaml
Updating `@walletconnect/ethereum-provider` to `2.20.0` which includes new AppKit Core
=> chore: update ethereum provider to 2.20.0

.changeset/itchy-stingrays-kiss.md, packages/connectors/package.json, pnpm-lock.yaml
Bump @coinbase/wallet-sdk to version 4.3.3 to include a [bug fix ](https://github.com/coinbase/coinbase-wallet-sdk/pull/1638) that addresses WalletLink connection issues.
=> chore: bump coinbase/wallet-sdk to 4.3.3

site/core/api/actions/readContracts.md
Replaced the outdated link to the Viem multicall documentation with the correct and current URL (https://viem.sh/docs/contract/multicall.html) in the readContracts API docs. This ensures users are directed to the right resource for multicall usage details.
=> fix(docs): update broken multicall link to current Viem documentation

.changeset/tricky-papayas-sparkle.md, packages/cli/src/plugins/fetch.ts
Add clearTimeout in catch block to ensure the timeout is properly cleaned up when a fetch request fails, preventing potential memory leaks during error handling
=> fix: prevent timeout memory leak in fetch plugin

.changeset/cool-shrimps-poke.md, packages/connectors/package.json, pnpm-lock.yaml
- Fixes issue with Terser builds on Next.js `14.x` caused by `@coinbase/wallet-sdk` exports
```
static/media/HeartbeatWorker.2ab792ba.js from Terser
x 'import', and 'export' cannot be used outside of module code
,-[48:1]
48 | self.addEventListener('beforeunload', () => {
49 |     stopHeartbeat();
50 | });
51 | export {};
: ^^^^^^
52 | //# sourceMappingURL=HeartbeatWorker.js.map
`----
Caused by:
0: failed to parse input file
1: Syntax Error
Error: 
x 'import', and 'export' cannot be used outside of module code
,-[48:1]
48 | self.addEventListener('beforeunload', () => {
49 |     stopHeartbeat();
50 | });
51 | export {};
: ^^^^^^
52 | //# sourceMappingURL=HeartbeatWorker.js.map
`----
Caused by:
0: failed to parse input file
1: Syntax Error
> Build failed because of webpack errors
```
- …
=> chore: update @coinbase/wallet-sdk to version 4.3.6

site/react/api/hooks/useReadContracts.md
This PR improves the `useReadContracts` documentation page by:
- Adding the missing script setup block
```md
<script setup>
const packageName = 'wagmi'
const actionName = 'readContracts'
const typeName = 'ReadContracts'
const TData = 'ReadContractsReturnType'
const TError = 'ReadContractsErrorType'
</script>
```
- Including shared query imports sections to match other hook docs
```md
```
=> docs: Improve useReadContracts page with return type and Tanstack Query import details

.changeset/modern-ghosts-exercise.md, packages/core/src/connectors/mock.ts
The mock connector's `wallet_sendCalls` handler reads the `calls` array received from the Viem `sendCalls` [action function](<https://github.com/wevm/viem/blob/main/src/actions/wallet/sendCalls.ts#L136>), but that function doesn't attach the `from` address inside the calls array, and instead sends it as a separate argument [here](<https://github.com/wevm/viem/blob/main/src/actions/wallet/sendCalls.ts#L139>). This causes all transactions sent from this handler in the mock connector to have the zero address as the `from` address.
This PR reads the `from` argument from the parameters and, if it exists, attaches it to the params sent to the `eth_sendTransaction` RPC request.
=> fix: add missing `from` address to the `sendCalls` handler in mock connector

.changeset/forty-maps-retire.md, packages/core/src/actions/getCallsStatus.ts, packages/core/src/actions/sendCalls.ts
Adds the ability for clients to implement custom sendCalls and getCallsStatus. This will enable libraries like permissionless to support useSendCalls for smart accounts.
=> Use getAction for sendCalls & getCallsStatus

site/dev/creating-connectors.md
This PR fixes a documentation filepath directory name
=> Fix directory name from 'connector' to 'connectors'
